### ISSUE TITLE
What is to do to break earlier

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1043]
1. What is to do/change (CMakeLists.txt ?? ) to get an error if a compiler warning occurs?
2. What is to do/change (.travis.yml ??) to stop the test if an error occurs?

**Comment by CDanU** [comment]
I know that there are gcc [flags](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) for that but I don't know how one could make that more general with CMake so that for example Visual Studio also aborts.

For Travis: 
https://github.com/  travis-ci/  travis-ci/  issues/  1066
https://github.com/  alphagov/  paas-cf/  commit/  18f1fc96608eabe9ef10fc02bc2386350f191162
(I hate linking to other repos, so that's why the links are chopped up)
Using `set -e` at the right places should abort the travis build.

Another thing that can speed up the builds is running the tests in parallel, ctest has a `-j` option for that. Running the tests with `ctest -j 8` inside the build/tests/ dir reduced the time from ~20 to ~6 sec for my machine. I also don't know hot to set this up in the cmake scripts.

Inserting
```cmake
if(NOT DEFINED CTEST_PARALLEL_LEVEL)
  set(CTEST_PARALLEL_LEVEL 8)
endif()
``` 
into either the root or the test CMakeLists.txt for some reason is ignored.
