### ISSUE TITLE
indent_access_spec and indent_access_spec_body

### ISSUE THREAD

**Issue by Massimo-B** [uncrustify/uncrustify#1078]
Currently it is not possible to have both indent_access_spec and indent_access_spec_body enabled, as mentioned in the comments:
```
# Indent the code after an access specifier by one level.
# If set, this option forces 'indent_access_spec=0'
indent_access_spec_body         = true     # false/true
```
Why? This was different in some older version, so it was possible to get:
```cpp
class MyClass
{
    public:
        MyClass(const QString &_message);
        QMainWindow *mainWindow;
        const char  *tag;
};
```

**Comment by CDanU** [comment]
I don't know what is the reasoning behind this but that comment was made in the same commit which introduced the `indent_access_spec_body` option: uncrustify@1123
I don't know how I can directly link svn commits, so here is the release with that option:
[uncrustify-0.45](https://uncrustify.svn.sourceforge.net/svnroot/uncrustify/tags/uncrustify-0.45/src/options.cpp)

I do get your expected result with
```sql
# Uncrustify 
input_tab_size                  = 4
output_tab_size                 = 4
indent_columns                  = 4
indent_with_tabs                = 0
indent_class                    = true
indent_access_spec              = indent_columns
indent_access_spec_body         = true
# option(s) with 'not default' value: 7
#
```
So that comment should be removed.

The option `indent_class` is somewhat wonky as it does not indent the access_specs or comments on the first collumn, `indent_access_spec_body` only indents everything that comes after it, that means if you have something that is before the first access_spec it is not going to get the extra indent. 
Somewhat related: #1006

**Comment by Massimo-B** [comment]
Right, enabling `indent_class` did it:

```cpp
(cfg="https://bitbucket.org/massimo/test/raw/6ec98452d054022da1377a981129a233dc2a3e80/crusty-test_012.cfg" ; input="https://bitbucket.org/massimo/test/raw/6ec98452d054022da1377a981129a233dc2a3e80/crusty-test_012.h" ; uncrustify -v ; curl -s "$input" ; curl -s "$input" | uncrustify -l cpp -c <(curl -s "$cfg") )
uncrustify 0.64_d
class MyClass
{
public:
MyClass ( const QString &_message );
QMainWindow     *mainWindow;
const char*     tag;
};

Parsing: 114 bytes (114 chars) from stdin as language CPP
class MyClass
{
    public:
        MyClass(const QString &_message);
        QMainWindow *mainWindow;
        const char  *tag;
};
```
