### ISSUE TITLE
Space insertion on ignore: sp_sparen_brace=ignore does not work

### ISSUE THREAD

**Issue by simsieg** [uncrustify/uncrustify#1208]
Although `sp_sparen_brace=ignore` is set, a space after ')' and before '{' is inserted.

Code in test.txt:
for(i=0; i<ARRAY_LENGTH; i++){
     printf("%d, ",ARRAY[i]);
}

is fixed to

for(i=0; i<ARRAY_LENGTH; i++) {
        printf("%d, ",ARRAY[i]);
}

Command: 
`uncrustify -c default.cfg  -p debug.txt --set sp_sparen_brace=ignore -f test.c`
Debug file:
https://gist.github.com/simsieg/90f35cbe2fb41041ea8803315955f574
Version:
`uncrustify -v`
`Uncrustify-0.65_f
`

**Comment by CDanU** [comment]
I can confirm this.

**Comment by guy-maurel** [comment]
The line number is now space:1881
There is not any rule for a token ')' follows by a '{'.
uncrustify uses the default rule AV_ADD.

**Comment by gmaurel** [comment]
This is not a bug

**Comment by mihaipopescu** [comment]
@CDanU Because spacing defaults to `ADD` has revealed a lot of tokenization bugs along the years. Switching to ignore would deprive us of this "helper debug feature".

**Comment by CDanU** [comment]
@mihaipopescu Could you elaborate a bit more on this? 
The behavior to add spaces if a case is not handled should definitely not be desired. 

> There is not any rule for a token ')' follows by a '{'.

Shouldn't `sp_sparen_brace=ignore` be applied for the provided code?
If so, the OP is a good example for this as `ignore` is not acting as it should in this case.

I think that the change to `AV_IGNORE` will be unpreventable because of this and #820. All cases that relied upon `av` being `AV_ADD` will need additional handling/options.

**Comment by mihaipopescu** [comment]
> The behavior to add spaces if a case is not handled should definitely not be desired.
I'm not saying that it's desired from an user pov but I think that bugs created drives us to move further with the development by fixing the tokenizer.

**Comment by guy-maurel** [comment]
Right. But there are many 100 of such a situation.
The first one is the declaration of a variable, such as `int A;`
And many other more. Lot of work! I do not wish to do it.

**Comment by mihaipopescu** [comment]
I don't understand. Can you be more specific what you don't want to do ?
