### ISSUE TITLE
do have anybody a test file for the option sp_paren_paren?

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1342]
Making many tests with the version current, I cannot find any scenario where this option is active.
Can anybody help?

**Comment by CDanU** [comment]
Looking at the old SVN Repo this option comes with the very fist commit:
```git
Import release 0.0.5 
CommitDate: Thu Feb 23 00:20:18 2006 +0000
```

At that point in time the lang enum was defined this way:
```c++
enum
{
   LANG_C   = 1,
   LANG_CPP = 2,
   LANG_D   = 4,
   LANG_ALL = 7,

   FLAG_PP = 0x80,  /*<< only appears in a preprocessor */
};
```
So it got to be something for `D`

**Comment by guy-maurel** [comment]
Using the example `void f(int (__attribute__((foo)) x)) {}`
the option is not used, because the case is catch by the option `sp_inside_fparen`
`log_rule2(119): Spacing: line 1 [FPAREN_OPEN/FUNC_DEF] '(' <===> [CPP_CAST/NONE] 'int' : sp_inside_fparen[1274] ...`
Any proposal?

**Comment by CDanU** [comment]
I guess the option is not working then.
`sp_paren_paren` should be triggered if both `(` tokens are compared, only than the check for `(` `foo` is done. 
It might be caused because of the parenthesis types, one of the is an `FPAREN_OPEN` what is the other one? I think that the `FPAREN_OPEN` parenthesis should be some other (maybe new) type entirely. The parenthesis type should match either a macro parenthesis (do we handle those in some special kind of way?) or a noexcept parenthesis type ( we don't handle those yet, see [here](http://en.cppreference.com/w/cpp/language/noexcept_spec))

**Comment by guy-maurel** [comment]
#1348 is a proposal to make the option active
