### ISSUE TITLE
Windows Portability Issue

### ISSUE THREAD

**Issue by billwaters** [uncrustify/uncrustify#1538]
I just built the Release version of uncrustify with Visual Studio Express on a Windows PC (A).  When I take the .exe to another Windows PC (B), I get this error, "The application was unable to start correctly (0xc00007b)".  So, I think that means that there is dependency on A that does not exist or is not up to date on B.  Is there any way to do the build on A so that it is more easily ported to other Windows PCs?

**Comment by CDanU** [comment]
Uncrustify does not use any 3rd party libraries.  Everything that it needs is in the source code. 
You do need __CMake__ and optionally python and git (failsafe: used by default _if_ available, additionaly can be disabled in the CMakeCache.txt / CMake-gui if `NoGitVersionString` is enabled) to build it.

You mentioned that you have build it with VS, it might be that it adds some MSVC libs, in that case you will most likely need some  of the Visual C++ redists (I think the version of those depends on the compiler the builds the binary). 

If my assumption above is right that you computer A has all the libs because you have installed VC on it. Computer B is either not having those libs or too old versions.

**Comment by billwaters** [comment]
Thanks for the tips!

**Comment by billwaters** [comment]
I did need to install the "the latest supported Visual C++ redistributable packages for Visual Studio 2017".

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by CDanU** [comment]
can be closed
