### ISSUE TITLE
feature request: Save spaces before newline

### ISSUE THREAD

**Issue by Krizai** [uncrustify/uncrustify#1641]
Xcode default behaviour is to put spaces according to current indent level in newline-only lines. Uncrustify remove these spaces. It would be nice to add an option to indent such a newlines.

So let's suppose the input is (where _ represents space)
```
- (instancetype)init{
    int i = 1;
____
____
    if (self) {
        i++;
    }

    return self;
}
```

The expected output should have the same amount of spaces, while current actual output will remove all of them

**Comment by CDanU** [comment]
It is unlikely that we will do that. The problem is a fundamental one, apart from newlines we don't save white spaces as chunk/tokens (the amount of spaces/tabs between two chunks is saved within the chunks). They are all gone by the end of the tokenization process. 

To make possible what you want would mean to introduce a new token type and change all the places where we currently only ignore newlines and/or comments (currently we `use chunk_get_next/prev_ncnl`: _non comment, non newline_) to additionally ignore white space tokens, but of course only in the appropriate places. That could either be fairly easy but it is likely hat it is going to be the opposite. 

In the case of leading spaces it might be easier to maybe add the amount of spaces to newline chunks and alter the way they are processed in the output stages (writing to a file) to add them if needed. That also would require some changes in the tokenization so that two newline chunks won't become one newline chunk that acts as both.

You can of course see for yourself and report with what you have found out. If it is feasible we can flash out a proper solution based on your prototype. Do ask if you need any kind of help.

**Comment by Krizai** [comment]
My idea was to go simple way and add some additional "column" property for newline chunks and set it in the same way as they are set for normal chunks during indentation. In this way, we don't need to break current grouping of the newlines.

**Comment by gmaurel** [comment]
FFixed
