### ISSUE TITLE
Is there a possibility to ignore a special construction in the code?

### ISSUE THREAD

**Issue by haarse** [uncrustify/uncrustify#1827]
Hi,

I'm using uncrustify on a language that is nearly related to C. In this language there is a construction like this:
parm.0

This is treated by uncrustify as: parm .0 but I would like to have it as it is.
Is there any setting to say ignore everything that starts with parm. and continues, leave it as it is.

Example code:
{
i number;       
i = parm.0;
}

formatted with uncrustify and my config file:
{
    i number;
    i = parm .0;
}

# Uncrustify-0.67-87-d75a44aa9
input_tab_size                  = 4
indent_columns                  = 4
indent_with_tabs                = 0
# option(s) with 'not default' value: 3
#

Any solution would work.

Regards
Håkan

**Comment by mwoehlke-kitware** [comment]
Since AFAIK this is never valid syntax in C-like languages, you might try fiddling with `combine.cpp` to get it to take a (`WORD`, `NUMBER`) pair where the second token starts with `.` and split the second token into `MEMBER` (the `.`) and `NUMBER` (the rest of the second token). (I'm not sure though if `combine.cpp` is the best place for this transform, or if it can be better done at an earlier point, maybe even in `tokenize.cpp`.)

**Comment by mihaipopescu** [comment]
That's a good idea actually. You can then add `set WORD parm` in your config.

**Comment by mwoehlke-kitware** [comment]
> You can then add `set WORD parm` in your config.

I don't think that should be necessary; uncrustify already sees `parm` as `WORD` in e.g. `i = parm.0;`.

I am also wondering, since it isn't entirely clear from the OP, if there is something magical about `parm`, specifically, or just constructs like `<identifier>.<num>`. The latter would certainly make some sense (indeed there have even been C++ proposals that use that syntax).

If it's really the former, TBH it might be more convenient to just post-process the sources with `sed -r 's/parm[.] *(\d+)\b/parm.\1/g'`. Although, that said, `'s/\b(\w+)[.] *(\d+)\b/\1.\2/g'` might work...

**Comment by haarse** [comment]
Thank you very much for your suggestions.
I think I will for the post-processing.
I hope I can handle it with some clever regexp.

Regards
Håkan
