### ISSUE TITLE
NODISCARD produces a warning with linux

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1832]
Introduce with 8a5e91d9c74d7c52e02d22b042a20ecc80bd0eba, NODISCARD produces:
```.log
src/uncrustify.cpp:312:58: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 NODISCARD static int redir_stdout(const char *output_file)
```
What is to do?

**Comment by CDanU** [comment]
Are you sure that that happens in the master? All three uses of the `redir_stdout` function are capturing the return value of that function.

**Comment by mihaipopescu** [comment]
It's not that.. It's just that the compiler doesn't recognise that feature yet. It was introduced in c++17.
I think we need to put some more defines around that (like @mwoehlke-kitware did for VS).

**Comment by mihaipopescu** [comment]
I think for clang and gcc we can use `__has_cpp_attribute(nodiscard)`

**Comment by CDanU** [comment]
Ohh, it is a c++17 feature ... so what would be reasons against switching to C++17?

Ubuntu 18.04 ships with [gcc8](https://gcc.gnu.org/projects/cxx-status.html#cxx17) and somewhat surprisingly even on Windows [VisualStudio](https://blogs.msdn.microsoft.com/vcblog/2017/12/19/c17-progress-in-vs-2017-15-5-and-15-6/) already is in a good shape (even the basic stuff of their experimental filesystem works quiet nice with a bit of macro help).

**Comment by mwoehlke-kitware** [comment]
> so what would be reasons against switching to C++17?

...because you'd be excluding anyone with a compiler more than a year old? That probably means *everyone* on an LTS distribution. (Note: from poking on godbolt, it looks like `[[nodiscard]]` needs GCC ≥ 7.1 or clang ≥ 3.9.)

The cop-out, of course is to `#pragma GCC diagnostic ignored "-Wattribute"`, since it's not like the warning is harmful... OTOH, `__has_cpp_attribute(nodiscard)` only requires GCC ≥ 5.1 or clang ≥ 3.6, which is probably tolerable. (You'd still be excluding Red Hat 6, but C++11 support in GCC 4.8 isn't quite all there, anyway, so you'd basically be saying "fully functional C++11 compilers", which isn't nearly as restricting as "C++17 compilers". That's assuming those aren't *already* the minimum requirements...)

On a loosely related note, if you're willing to push that hard on the minimum required *compiler*, I would commend you to also require at least CMake 3.0 :smile:. (Actually, I wouldn't be surprised if that's not already an *effective* requirement...)

**Comment by mwoehlke-kitware** [comment]
(#1847 is merged; this should be closed now?)
