### ISSUE TITLE
Question: Aligning variable types after const

### ISSUE THREAD

**Issue by ChristofferGreen** [uncrustify/uncrustify#1851]
Hello,

We would like to align variable types on the type name but when they have const the alignment becomes incorrect.

Example:
```
int a;
int b;
const int c;
void* d = NULL;
const char* const e = 'c';
```

This is formatted by our uncrustify config as:
```
int               a;
int               b;
const int         c;
void*             d = NULL;
const char* const e = 'c';
```

But we would like to format it as:
```
      int         a;
      int         b;
const int         c;
      void*       d = NULL;
const char* const e = 'c';
```
Is there any way of accomplishing this?

Thank you.

**Comment by mwoehlke-kitware** [comment]
Write `int const` instead of `const int`?

Seriously, when you realize your C API is totally wonky because you wrote `const CSTR` thinking that was `char const*` (`CSTR` → `char*`), you will realize why this is a good idea. (True story!)

I'm not aware of any way to get what you want with uncrustify, currently, except that you can get the equivalent by always putting `const` to the right of what it modifies... and for unrelated reasons, I recommend doing that anyway. `const` *always* modifies whatever is to its immediate left. No exceptions, no way to read the type that gives you the wrong impression of what is being modified. It only modifies something to its right when it is the first word of a type, and if you don't read carefully, "something" might not be what you expect.

**Comment by mwoehlke-kitware** [comment]
In fact, your example gives another great argument for "const always goes to the right":
```c++
const int         c;
      void*       d = NULL;
const char* const e = 'c';
```

Your first line (reading right to left, because it's less awkward to translate to prose) reads: "a variable named 'c', which has the type 'int', and which is immutable". Your third line reads: "a variable named 'e', which is immutable, and is a pointer to 'char', and also the pointed-to 'char' is immutable.

Now... what's up with the indent on your second line? It just doesn't make sense. You *state* that you want that indent so that they align "on the type"... but that's not what you show. You *seem* to want the types to be separate from the `const` that makes *the declaration* immutable, but that's not what you have. That would be more like:

```c++
const int               c;
      void*             d = NULL;
      const char* const e = 'c';
```

...but that isn't much better. In the first line, the `const` that makes *the variable itself* immutable is on the LHS, but in the third line, it is on the RHS!

By contrast:
```c++
int const c;
char const* const e;
```

...reads "a variable named 'c', which is immutable, and has the type 'int'", and "a variable named 'e', which is immutable, and is a pointer to immutable 'char'". Much more consistent! Indeed, now we could ask for:

```c++
int         const c;
void*             d = NULL;
char const* const e;
```

...which plausibly accomplishes what seems to be your actual goal.

**Comment by ChristofferGreen** [comment]
@mwoehlke-kitware Thank you for your comments. It certainly is bit of an ambiguous thing to be asking for. I will ask the team about what we really want here when they are back from vacation.
