### ISSUE TITLE
Feature request: Align nested conditional operators

### ISSUE THREAD

**Issue by shhccie** [uncrustify/uncrustify#186]
At least in Java, sometimes using nested conditional operators is natural

<pre><code>
value =
    op == Operator.PLUS     ? (v1.getKey() + v222222.getKey())   :
    op == Operator.MINUS    ? (v1.getKey() - v33.getKey())       :
    op == Operator.MULTIPLY ? (v1.getKey() * v55555555.getKey()) :
                              (v1.getKey() / v2.getKey());
</code></pre>

When this happens, I'd like the operators to align with each other, that is, the question mark aligns with the question mark in other lines, the colon aligns with the colon in other lines, and the options, which are the value part of the conditional operator, should align with each other (Note in the above example the last line should align after the question mark of the previous line)

**Comment by jayvdb** [comment]
> (Note in the above example the last line should align after the question mark of the previous line)

I have raised that separately as #638 , and it definitely applies to C/C++.

As for the general construct you have here, in C this would typically be written as a switch.  I am surprised that switch wouldnt also be used in Java.

Do you know of some example open source Java code that uses nested ternary conditional operators would be used instead of switch in Java?

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by gmaurel** [comment]
No answer, we close.
