### ISSUE TITLE
README.md references test_cli_options.sh

### ISSUE THREAD

**Issue by nivekkagicom** [uncrustify/uncrustify#1901]
The README.md still references the script `test_cli_options.sh` which I presume was replaced by `test_cli_options.py`:

> The Command line interface (CLI) output is tested by the test_cli_options.sh script. It is located inside of tests/cli/ and operates on the subdirectories of that folder.

It is also not clear if running `test_cli_options.py` is still required as CLI testing appears to have been added to the CMake tests. If one is still required to run the script please update the README to reflect the correct script name. If the script is now obsolete please remove it from the README and delete the file.

**Comment by mwoehlke-kitware** [comment]
Wow, this has been wrong since 8f45f0dd65ca.

You *can* still run `test_cli_options.py` by hand, there is just usually no need, since CTest / the `update_cli_options` target are so much more convenient.

> It is also not clear if running `test_cli_options.py` is still required

That's what actually does the work.

**Comment by mwoehlke-kitware** [comment]
Other than `s/sh/py/`, that line isn't really *wrong*, it's just that most users will want to rely on that script being run by CTest, or, when adding options, by "building" the `update_cli_options` target, since that takes care of passing the right options to `test_cli_options.py`. Adding a sentence or two to that effect is probably sufficient. (The target should maybe have a warning that it will overwrite the test expected output files.)

**Comment by guy-maurel** [comment]
may I close?

**Comment by guy-maurel** [comment]
see #4285
