### ISSUE TITLE
How to run the tests with some more command options

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#1950]
I want to run the tests with a command such as:
`uncrustify -c a.cfg -f b.cpp -L A`

My question is: How to add the option **-L A**

**Comment by mwoehlke-kitware** [comment]
By "the tests", you mean `run_tests.py`?

There isn't an option right now to specify individual logging flags, but `-g` (`--debug`) will add `-p` and `-LA` to each test execution. The logs are written to the same location as the formatted output, with `.log` added to the file name. (Similar with the debug output, but `.unc` instead of `.log`.)

There was some debate if CTest should *always* use `-g`. Right now it doesn't, but let me know if you'd like to change that...

**Comment by gmaurel** [comment]
Yes, I mean all the tests.
But, if the travis is running for us, I cannot see the results produced as .unc and .log
Any better solution?

**Comment by mwoehlke-kitware** [comment]
Ah, you need it for *ci*? I think you'll need to change some of the Python code, then.

Or, if you don't mind a somewhat ugly solution, you could add something like:
```bash
for f in $BUILD/tests/results/*/*.{unc,log}; do
  echo ==============================
  echo $f
  echo ==============================
  cat $f
done
```
...to the CI script. Either way, that's going to produce... um... (looks)
...almost two *gigabytes* of output. I'm not sure what CI is going to like that...

**Comment by guy-maurel** [comment]
Where is -g to be put?

**Comment by mwoehlke-kitware** [comment]
I'd put it here:
https://github.com/uncrustify/uncrustify/blob/36f0078b000deed198f471cd0124e2fc7d9839b6/tests/CMakeLists.txt#L46
(Anywhere in the `COMMAND` part of that `add_test` will do.)

Be aware that's also going to produce almost 2 GiB of files on the CI server... not sure if there are any disk usage limits?

**Comment by mihaipopescu** [comment]
> Be aware that's also going to produce almost 2 GiB of files on the CI server... not sure if there are any disk usage limits?

That's not only going to increase the storage needs but also the test time. Writing 2GB of files will slow down the test time.

**Comment by gmaurel** [comment]
Right. But I wanted it for local running, or the only few tests per language, not for all.
