### ISSUE TITLE
Windows uncrustify always prints out unc_getenv

### ISSUE THREAD

**Issue by syrinxsean** [uncrustify/uncrustify#2030]
On Windows, every time uncrustify is run, it prints out the results of `unc_getenv`, mucking up the stdout output of uncrustify.

```
% echo "foo" | uncrustify -q --frag -
unc_getenv: name=HOME len=21 value=c:\cygwin\home\sahern
```

This comes down to line 38 in compat_win32.cpp:
```
   printf("%s: name=%s len=%d value=%s\n", __func__, name, (int)len, str.c_str());
```

Seems like this was possibly put in for debugging and never removed. Note: the implementation of `unc_getenv` in compat_posix.cpp does not have this printf.

**Comment by mihaipopescu** [comment]
Maybe it should have been a log instead of printf. Good find @syrinxsean! Can you make a quick PR with the fix?

**Comment by syrinxsean** [comment]
Honestly, I've never done a PR with github, and I'm not sure how it's done. (A branch? A fork?) Making things worse, I don't have CMake installed and configured on my (Windows) machine, so I really can't even test my change. Rookie problems, I know.

But the change is simply commenting out line 38 in src/compat_win32.cpp

**Comment by mwoehlke-kitware** [comment]
> A branch? A fork?

Yes, and yes. (Well, the branch technically isn't necessary, but I don't encourage working directly on master of any software you don't maintain, as you're likely to confuse yourself at some point when your master diverges from upstream.) Otherwise, one of us will probably get to it eventually, but if you're not building uncrustify yourself, I guess it doesn't help you much until the next release anyway?

> But the change is simply commenting out line 38 in src/compat_win32.cpp

@mihaipopescu suggested using the logger. Without knowing for certain that the line can just go away entirely, that would be the safer thing to do.

> I don't have CMake installed and configured

You don't need to configure CMake itself, and installation on Windows is straight forward (you can [download an installer](https://cmake.org/download/), and it should Just Work). The GUI is very user-friendly, especially for a project like uncrustify that has essentially no dependencies. Obtaining a compiler is much more challenging; do you already have Visual Studio?

**Comment by guy-maurel** [comment]
PR #2272 is a bugfix proposal.
Please test it and report.
