### ISSUE TITLE
Unmatched PP_IF_INDENT

### ISSUE THREAD

**Issue by FernandoGarcia** [uncrustify/uncrustify#2032]
Hi!

I would like to know what's the right way to declare this functions to make it compatible with Uncrustify.

```
#ifndef USE_ESP8266
  void requestAction(char* topic, byte* payload, unsigned int length)
#else
  void mqttData(void* response)
#endif 
{
}
```

I'm using this type of declaration because my code should be compatible with two different libraries.
The code works perfectly as it's now.

But Uncrustify is giving me this error:
```
Parsing: C:\Users\FERNAN~1\AppData\Local\Temp\input11894-15312-c1q8zq.cq89.h as language CPP
C:\Users\FERNAN~1\AppData\Local\Temp\input11894-15312-c1q8zq.cq89.h:1 Unmatched PP_IF_INDENT
```
Best regards.

**Comment by mihaipopescu** [comment]
Hi Fernando,

If you read our [wiki](https://github.com/uncrustify/uncrustify/wiki/Known-problems) you will see that Uncrustify has a hard time figuring out preprocessor definition paths because they are complicated. Remember that Uncrustify is not a compiler, it doesn't even have a preprocessor (you're not feeding with a list of defines) so it can't properly understand your code. As a matter of fact, a lot of text editors with simple syntax highlight support, have problems understanding code like that... and if a tool has a hard time understanding that code it's a good change a human will too.

At Unity, we are taking an advantage of this and use it as a way to enforce better coding practices.

In your case, there's no way around the fact that both functions are using the same block of code (even though the arguments are very different) and so I would just refactor the ifdefs probably like this;

```c
#ifndef USE_ESP8266
  void requestAction(char* topic, byte* payload, unsigned int length)
{
    process(...);
}
#else
  void mqttData(void* response)
{
    process(...);
}
#endif 
```

**Comment by FernandoGarcia** [comment]
Hi!

Thanks for your reply!

Your suggestion is impracticable because I have to duplicate a big amount of code as you can see [here](https://github.com/FernandoGarcia/FerduinoAquariumController/blob/master/Ferduino_with_webcontrol_beta/Webserver.ino).

Best regards.

**Comment by mihaipopescu** [comment]
Then try use this:
```c
/* *INDENT-OFF* */
#ifndef USE_ESP8266
  void requestAction(char* topic, byte* payload, unsigned int length)
#else
  void mqttData(void* response)
#endif 
/* *INDENT-ON* */
{
}
```

**Comment by FernandoGarcia** [comment]
It prevent the error but doesn't solve the problem.
In this case is preferable comment some lines before indent then uncomment again.
If this problem haven't a solution  you can close the issue.

```c
/*#ifndef USE_ESP8266
  void requestAction(char* topic, byte* payload, unsigned int length)
#else*/
  void mqttData(void* response)
//#endif 
{
}
```

Thanks!

**Comment by FernandoGarcia** [comment]
Your workaround works but this lines can make some users confuse.

I'll leave without this lines.

Thanks for your support!
