### ISSUE TITLE
line at space-cpp:569 never used

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2052]
With the source:
```.cpp
friend void          ::test::swap< >(future< T >&, future< T >&);
```
The condition at line 565
```.cpp
      if (  chunk_is_token(first, CT_TYPE)
         && first->prev != nullptr
         && (first->prev->type == CT_FRIEND && first->next->type != CT_DC_MEMBER))
```
is never reached
because at line 2021
```.cpp
   if (  !chunk_is_token(second, CT_PTR_TYPE)
      && (chunk_is_token(first, CT_QUALIFIER) || chunk_is_token(first, CT_TYPE)))
   {
      iarf_e arg = options::sp_after_type();
      log_rule("sp_after_type");
      return((arg != IARF_REMOVE) ? arg : IARF_FORCE);
   }

```
is reached before.
What is to do?

**Comment by mwoehlke-kitware** [comment]
I don't see how 2021 could be reached "first". However, I think the condition at 565 is broken; that bit of code is inside `if (chunk_is_token(second, CT_DC_MEMBER))` which, while not *exactly* the same, makes me wonder how `first->next->type != CT_DC_MEMBER` would ever be true.

Archeology says that this was added (9a2ad693b) to fix #1288, but I don't believe that was the correct fix. I believe the code *should* be:
```c++
      if (  chunk_is_token(first, CT_TYPE)
         && chunk_is_token(first->prev, CT_FRIEND)
         && !chunk_is_token(second->next, CT_TYPE))
```

That said, this code appears to be trying to force a space in e.g. `friend int::bar();`. However, the space isn't actually necessary there (even though I'd be inclined to hurt anyone that wants to omit it), which makes me wonder if that should return `sp_after_type` instead of `FORCE`.
