### ISSUE TITLE
Handle qmake .pro and .pri files

### ISSUE THREAD

**Issue by MartinDelille** [uncrustify/uncrustify#2065]
Would it be possible to handle `qmake` .pro and .pri files from https://www.qt.io/?

**Comment by mihaipopescu** [comment]
I don't think so. Can you paste some examples? From what I can see http://doc.qt.io/archives/qt-4.8/qmake-project-files.html they are very different from what uncrustify is doing.

**Comment by mihaipopescu** [comment]
This is a domain specific language. Uncrustify is focused primarily in targeting general purpose languages like C/C++/C#/Obj-C/Java etc. Because they are look-alike they share a fair amount of code. So I don't think it's possible to add this language without a huge amount of work and support from someone with some level of expertise with it.

**Comment by MartinDelille** [comment]
Qt framework target general purpose goal since it enable a developer to make an abstraction of the plateform when developping an user interface so it shares a common goal with language like C, C++ and Java.

It doesn't seem to be a big amount of work since `uncrustify` do already all what I need on C++ files but I'm not familiar with uncrustify codebase.

Would you accept a PR if I try to implement it myself? I would also need some little help at the beginning.

**Comment by guy-maurel** [comment]
Every PR are welcome.

**Comment by mwoehlke-kitware** [comment]
You're welcome to try, but... TBH you might have better luck forking uncrustify and ripping out all the bits that aren't needed for QMake, or even just starting from scratch (maybe looking at uncrustify's architecture for suggestions). I think otherwise you are going to run into some trouble with constructs like:
```
app_bundle {
	# Target for quick dmg generation
	quickdmg.commands += echo "Deploying quick dmg for $${TARGET}"
}
```
...which don't really correspond to any constructs in C/C++/etc.

Just in these few lines, there are a few things of that nature:
- Comments use `#`, not `//`
- Certain expressions take arbitrary tokens (unquoted shell script) on their RHS
- Some blocks are started with particular keywords and have no ()s anywhere
- Statements end at newlines, not with `;`

I think these sorts of things will make it difficult to write a tool that handles both grammar families "cleanly".

**Comment by MartinDelille** [comment]
Ok you're right: this should be a separated project.
