### ISSUE TITLE
build for Apple

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2070]
As written at release-steps.txt:66
```.txt
6. Build for windows via mingw (save the zip file)
...
  $ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw32.cmake ...
```

I would like to know if it is possible to build for apple OS.

**Comment by mwoehlke-kitware** [comment]
By "apple os", do you mean macOS? (Not iOS?) If so, you could just build it normally on the lowest version of macOS you want to support. (I've never tried to cross-compiling to macOS — actually, I, personally, have never tried to cross-compile, *period* — but [SO](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=2ahUKEwjhz-j3wM_eAhUKw4MKHcAZCycQFjACegQICBAB&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F693952%2Fhow-to-compile-for-os-x-in-linux-or-windows&usg=AOvVaw0Hi08jgbWN45d4xwb6h_Lr) suggests it may be possible.) Worst case, maybe there is a way to get Travis to do the builds...

That said, I'm not entirely convinced it's worthwhile. It's a little silly for a code formatting tool to not just tell people to build it themselves, since presumably our users are people that know how to build software :wink:. Also, macOS users can probably get uncrustify via homebrew. Windows is the odd duck in that it doesn't have anything like a central package repository.

**Comment by mihaipopescu** [comment]
Cross compiling might not work because Apple is very strict about this.
But we are already testing on mac with travis https://github.com/uncrustify/uncrustify/blob/master/.travis.yml#L73-L76 so why not configure travis to upload the builds to github releases page?
