### ISSUE TITLE
Incorrect handling of __pragma keyword

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2098]
Version: 0.68
Config:
sp_arith = add

// Test.cpp
`__pragma( CoverageScanner(cov-off) )`
`#pragma CoverageScanner(cov-off)`

// Output
`__pragma( CoverageScanner(cov - off) )`
`#pragma CoverageScanner(cov-off)`

__pragma should be handled exactly like #pragma.

**Comment by guy-maurel** [comment]
Please test #2136 and report

**Comment by arneforlie** [comment]
I'm not the OP, but I noticed that uncrustify commit 2ee7415 inserts a space before the (.
In my opinion, __pragma should behave like a function call.

Test case:
```
function(CoverageScanner(cov-off));
__pragma(CoverageScanner(cov-off))
```
Result:
```
function(CoverageScanner(cov-off));
__pragma (CoverageScanner(cov-off))
```
Expected result:
```
function(CoverageScanner(cov-off));
__pragma(CoverageScanner(cov-off))
```

[debug.txt](https://github.com/uncrustify/uncrustify/files/2751889/debug.txt)

For the record, the previous commit (5813ad3) does not add the space.

**Comment by guy-maurel** [comment]
As you can see in your debug.txt, we get for **(CoverageScanner(cov-off))** the type _PREPROC_BODY_ , not the type _FPAREN_OPEN_
We don't have a rule for that. So we get a space.

**Comment by arneforlie** [comment]
Yes, that is probably the technical reason for this regression.

But, I'm not sure that __pragma should be handled the same way as e.g #include and #pragma. The Microsoft documentation calls it a keyword (https://docs.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=vs-2017) and the example shows it without the space.
C99 and C++11 has standardized _Pragma and they call it an operator (similar to sizeof). And sizeof would not have a space inserted in front of the (.

In addition, since the space was not inserted before, I consider this a regression.

**Comment by guy-maurel** [comment]
#2164 is a bugfix proposal.
Please test and report

**Comment by arneforlie** [comment]
I notice that _Pragma (standardized by C99 and C++11) and __pragma behave differently. Is that intentional?
Test case:
```
__pragma(CoverageScanner(cov-off))
_Pragma(CoverageScanner(cov-off))
```
Output:
```
__pragma(CoverageScanner(cov-off))
_Pragma(CoverageScanner(cov - off))
```
[debug.txt](https://github.com/uncrustify/uncrustify/files/2809720/debug.txt)
