### ISSUE TITLE
Indentation of switch/case is confused by #ifdefs

### ISSUE THREAD

**Issue by uwerat** [uncrustify/uncrustify#2150]
Using origin/master f72c97d40761ecdd963dfc8cf2b17a900f30ebb3 ( 19/01/04 )

Running with default settings:

```
int f( int a )
{
    switch ( a )
    {
        case 1:
        {
            return a;
        }
        case 2:
#if 1
        case 3:
#endif
        {
            return a;
        }
    }
}
```

The result has a wrong indentation for block below the second case:

```
int f( int a )
{
	switch ( a )
	{
	case 1:
	{
		return a;
	}
	case 2:
#if 1
	case 3:
#endif
		{
			return a;
		}
	}
}
```

**Comment by mihaipopescu** [comment]
There are known caveats formatting code with PP. Not only formatters struggle with them but also IDEs, mainly because they are not compilers and can't format all PP branches properly. We have some examples in our FAQ as well. 

On the other hand, we're turning this around and say it's not entirely a defect and that enforces cleaner code. If a simple parser can't understand the code it's likely a human won't too.

**Comment by guy-maurel** [comment]
PR #2298 is a bugfix proposal.
Please test it and report.
