### ISSUE TITLE
Problem with sp_before_angle 

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2187]
```
# Uncrustify-0.68
sp_before_angle = remove
sp_compare      = add
```

Input (no changes are expected)
```
void test()
{
    CallFunc( a < 1 || a > 2 );
    CallFunc( a < 1 || a > b );
}
```

Output
```
void test()
{
    CallFunc( a < 1 || a > 2 );     // OK
    CallFunc( a< 1 || a > b );      // Space was removed before the <
}
```

It looks like the "<" is not recognized as a comparison operator on the second line.

**Comment by mwoehlke-kitware** [comment]
Whee!

I bet what is happening is that uncrustify is parsing the second line as a local function declaration. This isn't *entirely* unreasonable, since `func(type b)` is legal C code, and `a<1||a> b` might be a legal parameter declaration in C++. In fact, I think C++ requiring a return type (unlike C) may be the only thing that disambiguates this, though I suspect uncrustify is not applying that rule.

Just for fun... what is the correct parse of this?
```c++
void test()
{
    A < 1 || 2 > bar( A < 2 || 3 > x );
};
```

The correct answer is... you can't tell without *knowing* what at least `A` is. Uncrustify will never¹ be able to parse that correctly 100% of the time. (Moreover, I could probably write surrounding code for both possible parses that would turn that into reasonable code. Granted, at least one would involve implementing side effects in an `operator<` and/or `operator||`, but it's *possible*...)

(¹ **Never**. To do so, it would have to be a fully functioning C++ parser, which *includes* implementing complete preprocessing... and we specifically *don't* want to do that, because then we wouldn't be able to format code that doesn't exist after, or is modified by, preprocessing.)
