### ISSUE TITLE
Crash on namespace alias inside function

### ISSUE THREAD

**Issue by elnull** [uncrustify/uncrustify#2387]
Current uncrustify version crashes on following code:
```
namespace b{}
void f()
{
namespace a = b;
}
```
This code processed fine:
```
namespace b{}
namespace a = b;
void f()
{
}
```

**Comment by mwoehlke-kitware** [comment]
Even simpler:
```c++
namespace a = b;
```

It crashes because [`newlines_cleanup_braces`](https://github.com/uncrustify/uncrustify/blob/1bc0703962ad6843529df225d09fa8d814297c7f/src/newlines.cpp#L3739-L3749) is looking for a closing brace and unconditionally trying to do stuff with it. It looks like this logic does not understand that `namespace <word>` doesn't necessarily start a namespace scope; it could be an alias instead.

**Comment by mwoehlke-kitware** [comment]
Thanks for the report, @elnull! If you can, please try #2388 on your full code. I taught it to recognize namespace aliases and not look for a closing brace for those, and also to not crash if the brace is missing. (However, it will now throw an error if it expects a brace and does not find one. It's possible this will break on valid code, though previously it would almost certainly crash in such cases, so probably it will never be worse than before.)

**Comment by elnull** [comment]
Patch #2388 works well on my code. Thank you, @mwoehlke-kitware !

**Comment by mwoehlke-kitware** [comment]
Thanks for testing! The patch has been merged :slightly_smiling_face:.
