### ISSUE TITLE
Possible C++ bug with nl_func_proto_type_name

### ISSUE THREAD

**Issue by aste4** [uncrustify/uncrustify#2391]
Version 0.69.0_f
```
int main()
{
    std::ifstream file("input.txt");
}
```

**nl_func_proto_type_name = add**

**Expected**: 
```
int 
main()
{
    std::ifstream file("input.txt");
}
```
**Actual**:
```
int 
main()
{
    std::ifstream 
    file("input.txt");
}
```

**Comment by mwoehlke-kitware** [comment]
I can't reproduce:

```
$ echo $'int main()\n{\n    std::ifstream file("input.txt");\n}' | uncrustify -c <(echo 'nl_func_proto_type_name add') -lCPP
Parsing: 52 bytes (52 chars) from stdin as language CPP
int main()
{
        std::ifstream file("input.txt");
}
```

Maybe it is fixed in master?

Note that, without `nl_func_type_name` as in your original post, I am not getting a newline before `main`. I guess you are using more than just the one config option; maybe something else in your configuration is causing it? Please post a *complete* input file and configuration necessary to reproduce the issue.

**Comment by aste4** [comment]
Error on my part.

It works as expected. I was mistakenly parsing it as C instead of CPP
