### ISSUE TITLE
what should nl_template_class do?

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2417]
The option **nl_template_class** is not really clear!
Reading it first I anderstand _template NL class_.
But the text is:
Add or remove newline between 'template&lt;&gt;' and whatever follows.
Whatever is not what I wish.
The file option.h uses it at different places:
```.txt
 37: template<typename T> class Option;
132:    template<typename V> friend bool read_enum(const char *s, Option<V> &o);
        template<typename V> friend bool read_number(const char *s, Option<V> &o);
169: template<typename T>
     class Option : public GenericOption
192:    template<typename V> friend bool read_enum(const char *s, Option<V> &o);
        template<typename V> friend bool read_number(const char *s, Option<V> &o);
203: template<typename T, T min, T max>
     class BoundedOption : public Option<T>
242: #define UNC_IMPLEMENT_OPTION(T)                                     \
       template<> option_type_e Option<T>::type() const;                \
       template<> const char *const *Option<T>::possibleValues() const; \
       template<> bool Option<T>::read(const char *s);                  \
       extern template class Option<T>
```
These are 3 different uses. I think, we should have at least 3 options for that.
Please, comment!

**Comment by mwoehlke-kitware** [comment]
Hmm...

The unit tests are consistent with the documentation, although that argues that the name ought to be `nl_after_template_???` (where I'm not sure what `???` should be). But you are right, there are several possible use cases:

- A template class/struct forward declaration
- A template class/struct definition
- A template variable
- A template function declaration
- A template function definition
- A template friend declaration

...as well as specializations of the above.

The pattern in option.h seems to be "nl in definition, no nl in declaration".

I think we should at least differentiate declarations vs. definitions. I suppose plausibly we might want:
- `nl_template_{class,func,var,friend}`
- `nl_template_{class,func,var,friend}_{decl,def}`
- `nl_template_{class,func,var,friend}_{decl,def}_special`

We can easily punt on the `_special` override and add it some other time. We could also, I suppose, punt on the `func`/`var`/`friend` variants and continue as now using `nl_template_class` for everything. (And we could certainly treat `friend` as `func` to start with.) However, I suppose we do want to go ahead and add the `_decl`/`_def` overrides? (My thinking is to do what we have done elsewhere; a more specific option overrides a less specific option, otherwise fall back to the less specific option.)

**Comment by guy-maurel** [comment]
We need to complete the file _forUncrustifySources.cfg_, to be sure that all the options which have any effect on the sources, are set to an appropriate value. This is NOT the case here, with the option _nl_template_class_, as shown above.
We need to make necessary to have a dependency with introducing a new option and complete the file _forUncrustifySources.cfg_ . How to do that?

**Comment by mwoehlke-kitware** [comment]
I don't understand the question?

As of writing, there is no configuration which will preserve the existing formatting. Given that the existing style in uncrustify, as well as the style my own projects tend toward, this is... unfortunate.

I propose:
- Modifying `nl_template_class` to *only* apply to class templates (not functions, variables or type aliases).
- Adding new options for template {functions, variables, type aliases}.
- Adding additional options which will override the more general `nl_template_class` and new friends (per previous point) for declarations or definitions.

I've started working on that [here](https://github.com/mwoehlke-kitware/uncrustify/tree/nl_template-tuning), but a) it needs new tests, still, and b) there is a possible bug parsing classes derived from templated classes.

Right now, I am using `PCF_LVALUE` to differentiate between class definitions and class declarations. I'm not sure if this is "correct", but it fails for classes that derive from a templated type. (Is this a bug? I'm not sure what `PCF_LVALUE` is supposed to represent...) Is there a different/better way to tell a class [forward] declaration from a class definition?

**Comment by mwoehlke-kitware** [comment]
BTW, adding to `forUncrustifySources.cfg`:
```
nl_template_class_decl                    = remove
nl_template_class_def                     = force
nl_template_func_decl                     = remove
nl_template_func_def                      = force
nl_template_var                           = remove
nl_template_using                         = remove
```

...produced three changes:
- [src/ListManager.h:21](../tree/429cc2f9/src/ListManager.h#L21) (added)
- [src/enum_flags.h:37](../tree/429cc2f9/src/enum_flags.h#L37) (added)
- [src/option.h:203](../tree/429cc2f9/src/option.h#L203) (removed)

The first two are consistent with the majority of our existing declarations. (For fun, I tried setting everything to `remove`, and it changes a lot more code.) The second also qualifies as "my bad" :wink:. The third is the aforementioned bug; given `nl_template_class_def = force`, it is clearly wrong.

FYI, I am probably not going to have this finished until next week. If you are in a hurry and would like to add some tests to my branch and/or look at the "bug", please feel free!

**Comment by guy-maurel** [comment]
No. It is not "hurry", but it must be done.
