### ISSUE TITLE
logical & operator misinterpreted as reference operator

### ISSUE THREAD

**Issue by byron-hawkins** [uncrustify/uncrustify#2427]
This issue is identical to #2151, except that the operator `==` is somehow not regarded as a boolean operator, which prevents the fix #2299 from taking effect.

The correct code (space after `_index`):

    return (_index & Compressor::terminalDifferentiatorBit) == 0;

Semantically obscured by uncrustify (lost the space after `_index`):

    return (_index& Compressor::terminalDifferentiatorBit) == 0;

I tested the fix #2299 by changing `==` to `&&` and uncrustify does apply the fix in that case. So the problem is related to the `==` operator. 

Sorry I don't have a minute to send all the other files and stuff that you request with bug reports. But this is all the info you need right here.

**Comment by mwoehlke-kitware** [comment]
Um... I [have a fix](https://github.com/mwoehlke-kitware/uncrustify/commit/fix-non-casts), but it's currently still failing this case:
```c++
return (_index & Compressor::terminalDifferentiatorBit) + 0;
```

More digging is needed...

**Comment by mwoehlke-kitware** [comment]
Well, I suspect the fix is to teach `fix_casts` to do a better job of identifying things that actually could be casts. Your case is easy, because a `&` can only appear either at the end of a type, or as `(&)` (optionally followed by `[]`s, with or without a size, or by a function parameter list). Things get a little more tricky if your `&` is replaces with `*`... but even so, after a `*`, the only new thing we could have is qualifiers.

The existing code *looks* fairly complicated, but it is actually quite simple-minded compared to what is needed. For example, this C-cast is not being parsed as such:
```c++
(int**(*)(float)x;
```

What we really need here is correct type parsing, which incidentally would solve your issue without the #2299 fix. To wit:

- *complete-type*:
  - [ *qualifiers* ]
  - *scoped-identifier* | *unqualified-type*
  - [ *indirection* ]
  - (null) | `&` (C++) | *array* | *function*

- *unqualified-type*:
  - **TYPE** [ *unqualified-type* ]

- *scoped-identifier*:
  - [ *scoped-identifier* `::` ] (C++)
  - **WORD** | **TYPE**
  - [ *template-arguments*¹ ] (C++)

- *qualifiers*:
  - **QUALIFIER** [ *qualifiers* ]

- *indirection*:
  - *qualifiers* | `*`
  - [ *indirection* ]

- *array*:
  - `(*)` | `(&)` (C++)
  - [ *subscript* ]

- *subscript*:
  - `[`
  - [ *expression* ]
  - `]`

- *function*:
  - `(`
  - [ *scoped-identifier* `::` ]
  - `*` | `&` (C++)
  - `)`
  - `(`
  - [ *parameter-list* ]
  - `)`

- *parameter-list*:
  - *complete-type*
  - [ `,` *parameter-list* ]

...Yeah. We need to handle *all that mess*. It's *do-able*, per the above specification, but it's clearly a lot more complicated than the token-soup approach we are currently taking. I suspect doing so will fix a bunch of bugs.

(¹ Already implemented; see `skip_template_next`.)

**Comment by mwoehlke-kitware** [comment]
Ugh... so, I took a stab at implementing that, and it turns out it *doesn't help* :cry:.

Consider this simplified example from the test suite (which is very similar to the example in https://github.com/uncrustify/uncrustify/issues/2427#issuecomment-538059583):
```c++
a = (c) + (d);
```

Is this a C-style cast? Well...

```c++
// No
int a, c, d;
a = (c) + (d);

// Yes
using c = int;
int a, d;
a = (c) +(d);
```

...then there are more fun gems:
```c++
return (foo<int>::bar)(x);
```
Not only can uncrustify not tell, I could define `foo` in such a way (using specialization) that it could be a cast or a function call, depending on the template parameter. Oy.

At this point, I'm open to suggestions? (Maybe err on the side of not-a-cast?)

**Comment by byron-hawkins** [comment]
If you can limit the formatting of a cast to situations where there is no doubt, that would work fine for me. It's not often that I accidentally mis-format an ampersand, so I don't really need much help from uncrustify there. Alternatively, could you add a configuration option for this, maybe `cautious_cast_formatting`?

**Comment by gmaurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
```.txt
Uncrustify_d-0.73.0-101-f7992ec5
Parsing: byron-hawkins.cpp as language CPP
return (_index & Compressor::terminalDifferentiatorBit) == 0;

```
