### ISSUE TITLE
sp_word_brace has no effect?

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2428]
Config:
```
# Uncrustify-0.69.0
sp_word_brace = remove
 ```

Input:
```
void test()
{
    int a { 0 };
}
```

Output (nothing changed):
```
void test()
{
    int a { 0 };
}
```

Expected output:
```
void test()
{
    int a{ 0 };
}
```

Unless I am misunderstanding the option, I can't make it to work, whatever the value is (remove, force, add).

**Comment by mwoehlke-kitware** [comment]
Hmm... `sp_type_brace_init_lst` is being applied, which is not horribly shocking, but does indeed seem wrong. In fact, I can't see that `sp_word_brace` is ever applied. (AFAICT there are no tests for it, either.)

Another "seems wrong" spot is e.g.:
```c++
foo::foo() : m_x{0} {...}
```

Here too, it seems `sp_word_brace` should be used, but `sp_func_call_paren` is being used (the braces are being parsed as `FPAREN_{OPEN,CLOSE}`).

Part of the problem is that we aren't properly marking types associated with initializer lists. For example:
```c++
auto x = y{...};
```

We correctly parsed here that the `{...}` is an initializer list, but failed to mark `y` as a `TYPE`. I suspect that, because of this, `sp_type_brace_init_lst` actually gets applied to either `TYPE` *or `WORD`* followed by a braced initializer list.

Thus, my guess is that there are two fixes:
- Deprecate `sp_brace_word` and rename `sp_type_brace_init_lst` to `sp_before_brace_init_lst` (and, ideally, document that it doesn't apply to member initializers).
- Do better marking types associated with braced initializer lists, and fix `sp_type_brace_init_lst` to only work after `TYPE`, not `TYPE` or `WORD`. (Presumably the existing `sp_word_brace` code will then work as intended.)

**Comment by guy-maurel** [comment]
PR #2609 is a bugfix proposal.
Please test it and report.

**Comment by guy-maurel** [comment]
May I close?

**Comment by guy-maurel** [comment]
```.cpp
{
    int a{ 0 };
}
```
The space between **a** and **{** is controled by _sp_word_brace_init_lst_ , which is correct

**Comment by chris-mich** [comment]
I will try version 0.72 before the end of the year, I will let you know!

**Comment by chris-mich** [comment]
Works fine with version 0.73 using "sp_word_brace_init_lst = remove", Thank you!! 👍
