### ISSUE TITLE
Is there any sort of stability guarantee?

### ISSUE THREAD

**Issue by Minoru** [uncrustify/uncrustify#2449]
Hello! I couldn't find an answer in the README and wiki, so: does Uncrustify makes any promises about keeping the old formatting as new versions come out? Can I just create a config and be sure that no matter what Uncrustify version I use, the result will be the same (save for bugs in Uncrustify)?

I can see the latest version is 0.69.0, which implies there's no guarantees—but maybe Uncrustify just doesn't use semantic versioning.

**Comment by mwoehlke-kitware** [comment]
In general, yes, we try not to break things that aren't broken.

That said, note that we do sometimes become "less strict" about formatting. That is, a formatting change that an old version would have made might not be made by a new version (given the same configuration). This can happen because e.g. we discover that an option was being applied in too many situations.

`nl_template_class` is a good example. Historically, this applied to pretty much *any* use of `template`. But that is too coarse. I am working on a PR (mostly it is pending on some other changes) that will break this into several options. As a result, where uncrustify might have previously always forced (or removed) a newline (or space, in case of `sp_*` options), a new version might leave your code as-is. However, the most common such "breakage" is of this nature, where something that previously would have been formatted would become unformatted (as in, the formatting is not altered).

**Comment by Minoru** [comment]
Thanks for a blazing-fast response! I was mostly concerned about two people using different versions, constantly re-formatting the same code back and forth. But if the newer version usually takes a more related approach, it seems I'll be fine in this situation.

My question is answered, so I'm closing this. Thanks once again!
