### ISSUE TITLE
how to find the block

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2566]
Ref. #2281 

**Input:**
```.cpp
int foo(int op)
{
    switch (op)
    {
        case 1:
            do_something();
        break;
        case 2:
            do_something_else();
        case 3:
            if (do_something_different())
            {
                do_this();
            break;  // this should be indented like the surrounding code
            }
            do_something_more();
        break;
    }

    for (;;)
    {
        break;
    }
}
```
The problem is: There are some break in the code.
How to find? ie. is the last **break** in the for-block or in the switch-block?

**Comment by chrisemb** [comment]
I think for each (virtual) brace level kind of flag “top_brace_level_inside_switch” could help.

Then a `break` is relevant if the flag for the corresponding brace level is set.

In that case the `break` inside the if-block of your input would be on the wrong brace level (hence no flag set) and the last `break` in the for-block would not have the flag set either (because brace level entered not inside `switch`).

But I'm not familiar with the internal structure of uncrustify. So, if my comment does not help, please ignore it.

**Comment by chrisemb** [comment]
After a short look into the description and some sources (not sure if I’m missing some chunks in the hierarchy):
Is it sufficient for the `break` to have chunk type of parent CT_BRACE_OPEN and the next parent CT_SWITCH?
