### ISSUE TITLE
Wrong formatting of operator within namespace

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2771]
Configuration:
```
# Uncrustify-0.70.1
indent_class             = true
align_func_proto_span    = 1
align_single_line_func   = true
align_on_operator        = true
nl_func_leave_one_liners = true
```

Input (no changes are expected): 
```
class CDiagnostic
{
	CDiagnostic& operator<<( int value_ ) { return ns::operator<<( *this, value_ ); }
};
```

Output:
```
class CDiagnostic
{
	CDiagnostic&                                   operator<<( int value_ ) { returnns::operator<<( *this, value_ ); }
};
```
Two problems here:

1. Excessive spaces were added
2. Space between **return** and **ns** was removed (code does not compile anymore)

Note that the problem disappears if I remove **ns::**

**Comment by guy-maurel** [comment]
Well, what is "ns" ?
A class, a struct or a namespace ?
Could you give me your e-mail address to guy.j@maurel.de ?

**Comment by mwoehlke-kitware** [comment]
In this case, I believe it *must* be a namespace, but I don't think it should matter.

It looks like the operator alignment code is broken. I wonder if it is trying to align the `<<` as if the `ns::operator` (at least, the `ns::`) does not exist? Note that removing `align_on_operator = true` causes the problem to disappear, which is why I suspect that code. (Turning off just about anything *else* also causes it to go away, but likely because removing those options also result in `align_on_operator` not being applied for the test case.)

**Comment by chris-mich** [comment]
Yes, "ns" is a namespace.  I simplified the sample, but I think we had two levels (ns::cls::) in our case.
Vous avez déjà mon courriel Mr Maurel. ;-)

**Comment by guy-maurel** [comment]
Non, pas encore. Domage!

**Comment by guy-maurel** [comment]
PR #2797 is a bugfix proposal.
Please test it and report.

**Comment by chris-mich** [comment]
Looks good in version 0.73, thank you!
