### ISSUE TITLE
UNCRUSTIFY_VERSION suffix '_f' is causing trouble with Debian package

### ISSUE THREAD

**Issue by carlolars** [uncrustify/uncrustify#2782]
The UNCRUSTIFY_VERSION has an `_f` as suffix which is not working well when using `cpack` to create a Debian package as it is rejected when trying to install:  
`error in 'Version' field string '0.71.0_f': invalid character in version number`

My workaround is to pass the `-R <packageVersion>` argument to `cpack`:
```
cpack -G DEB -D CPACK_DEBIAN_PACKAGE_MAINTAINER="me" -R 0.71.0
```

Would it be possible to skip the `_f` suffix, or at least removed it from CPACK_PACKAGE_VERSION?

**Comment by CDanU** [comment]
I am a bit surprised that this comes up again, I know that the debian guys up to this point had patches applied to uncrustify. 
Presumably the `_f` suffix https://github.com/uncrustify/uncrustify/blob/3357ad67076dd68d45d47cc06e96b7ad3824a8a7/CMakeLists.txt#L132 was patched out. What has changed about this?  
I added the prefix in order to know that someone loaded the sources an we can't be entirely sure which commit state they have. The suffix is used when you don't have a git history or disabled the according option.

**Comment by carlolars** [comment]
The absolute minimal fix for making it work (for debian packages) is to just replace the underscore with a hyphen. But that would make the deb-package always have the suffix even when the binary is without a suffix, which is not optimal but at least it will work.
