### ISSUE TITLE
align_func_proto(87): pc->level is 9. This is too big, at line 11, column 71. Make a report, please.

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#3001]
```
# Uncrustify-0.72
align_func_proto_span = 1
```

Input:

```
void Func()
{
    switch ( cond )
    {
        case 0:
        {
            for ( const auto type : GetMetricTypes() )
            {
                ColumnAdd( [ this ]()
                           {
                               return CValue( m_metrics[ static_cast< int >( type ) ] );
                           } 
                         );
            }
        }
    }
}
```

We get this error message when trying to format this code using version 0.72.  Unscrustify simply stops.
This used to work in version 0.71.
We can't upgrade to 0.72 because of this bug...
It happens in many different files in our source code; this is the most simplified example I could find.

Seems to be related to "align_func_proto_span = 1".

**Comment by guy-maurel** [comment]
The problem is already solve.
The current git version have been set up to 16.
You have to download and compile it.
If you cannot do it, I can send you a new version which is about 9 MByte

**Comment by chris-mich** [comment]
OK thank you!  We will simply wait for version 0.73.

**Comment by guy-maurel** [comment]
It will be May 2021

**Comment by micheleCTDE** [comment]
I had the same issue on 0.72.0. I backported commit 64d93e3fb and this problem does not show up any more.
Just wondering what is the rational in choosing 16 rather than 24 or 32 or any other value. Meaning: what is the side effect problem is we have more than 16 levels?

On a side note, we are going to use a customized uncrustify on a huge code base (about 200 repos, >200K files, a few millions (maybe 8) line of codes), so if it helps to have more stable releases, I will be happy to run some comparison tests before you make a new release. Just ping me at my email address or here.

Final note. I don't mean to tell you how to do your releases, but issue 2976 and this one seems quite major to me. De facto makes release 0.72.0 almost unusable on large code bases. Personally, we use a customized version of uncrustify so it does not affect us much, but I would consider a 0.72.1 release if I were you.

**Comment by guy-maurel** [comment]
> Just wondering what is the rational in choosing 16 rather than 24 or 32 or any other value. Meaning: what is the side effect problem is we have more than 16 levels?
You are right, 23 is also a pretty number!
There are not any side effect, I only need to do it , or somebody else with vector.h

> On a side note, we are going to use a customized uncrustify on a huge code base (about 200 repos, >200K files, a few millions (maybe 8) line of codes), so if it helps to have more stable releases, I will be happy to run some comparison tests before you make a new release. Just ping me at my email address or here.
It would be fine...

> Final note. I don't mean to tell you how to do your releases, but issue 2976 and this one seems quite major to me. De facto makes release 0.72.0 almost unusable on large code bases. Personally, we use a customized version of uncrustify so it does not affect us much, but I would consider a 0.72.1 release if I were you.
I don't have enought time to work on all the issues. I have to make a choose.
I make a new release every 6 months, May and November

**Comment by micheleCTDE** [comment]
Thanks for the feedback Guy.
16 works fine in my limited testing so far (3200+ source files). Once I extend it to a bigger code base, I will update you if I run into the same issue.

Btw, since the problem here is solved, shouldn't this issue be closed? :wink:
