### ISSUE TITLE
Option deprecation is not silenced by '-q'

### ISSUE THREAD

**Issue by kraiskil** [uncrustify/uncrustify#3288]
According to `uncrustify --help`, the `-q` option should supress any output to stderr.
```
 -q           : Quiet mode - no output on stderr (-L will override).
```

Option deprecation warnings are not supressed by it as shown by this
```
$ echo indent_sing_line_comments = 0 > uncrustify.cfg
$ uncrustify -q -c uncrustify.cfg
uncrustify.cfg:1: option 'indent_sing_line_comments' is deprecated; did you want to use 'indent_single_line_comments_before' instead?
$ uncrustify -q -c uncrustify.cfg 2> /dev/null
$ uncrustify -v
Uncrustify_d-0.73.0-105-704034b8
```

If this is a bug in the documentation and not functionality, is there a better way of handling deprecated options than just making sure everybody in the team has the exact same version of the uncrustify binary?

**Comment by guy-maurel** [comment]
@mwoehlke @micheleCTDE  What do you think about?

**Comment by micheleCTDE** [comment]
Since '-q' is supposed to be quiet, I think it makes sense to suppress the warning when it is used. When '-q' is not used, the user would have the message as normal.

@kraiskil: regarding working with uncrustify in a team, I think having the same version is a requirement, since different uncrustify versions may do different things even with the same set of options as a result of continuous bug fixing. That is what we will do on our project (in fact we maintain our own project-fork of uncrustify).

**Comment by micheleCTDE** [comment]
Looking at the code, '-q' is an option related to masking logging information. stderr is used in several parts of the code to report errors.
So if we want '-q' to suppress all writing to stderr, there will be quite a bit of changes to do. 
Otherwise the documentation should probably be adjusted and specify that -q refers to blocking logging info from being sent to stderr.

**Comment by guy-maurel** [comment]
PR #4291 is a bug fix proposal.
Please test it and report.
