### ISSUE TITLE
Unexpected indent in function declaration when parameter type is user defined

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#3291]
Given the test case below, why does Uncrustify indent foo2, but not the two others which are semantically identical?

Test code:
```
using Bar = int;

void
foo1(Bar b);

void
foo2(Bar);

void
foo3(int);
```
Generated output:
```
using Bar = int;

void
foo1(Bar b);

void
        foo2(Bar);

void
foo3(int);
```
Expected output is identical to input.

[debug.txt](https://github.com/uncrustify/uncrustify/files/7026184/debug.txt)

**Comment by guy-maurel** [comment]
It is a known problem.
uncrustify doesn't interpret the first line to work on line 7.
You can help with the set option:
`set type Bar`

**Comment by arneforlie** [comment]
Are you also implying that it is unfixable?
The set option isn't really viable because we want to use Uncrustify on a large amount of source code, so having to specify each and every user defined type does not scale.

Our current solution is to use AStyle post-process the output from Uncrustify to fix things like this. But we would very much like to remove our dependency on AStyle since it is now an unmaintained project.

**Comment by guy-maurel** [comment]
Give me some more time.
I'm trying on the first line.
I think, it might be possible to fill a table within tokenize.cpp with the data from the "using..." line.

**Comment by guy-maurel** [comment]
Do you know how AStyle is doing the work?

**Comment by arneforlie** [comment]
Sorry, I have no idea how AStyle does its work.
Just to be clear, AStyle has a fair amount of issues, and sometimes AStyle changes the output from Uncrustify in an undesirable way. But the current setup of Uncrustify followed by AStyle does a slightly better job than Uncrustify alone.

**Comment by arneforlie** [comment]
I'm not sure your proposed solution of filling the table from using (and typedef) lines will work well. Most of the user defined types will be declared in a header file, and Uncrustify will not see those. The test cases I write are intentionally minimal, and not always representative for the real world.

**Comment by micheleCTDE** [comment]
Hi @arneforlie,
Last december I evaluated AStyle, clang and uncrustify in depth. I find Astyle to be the weakest of the three. clang does a neat job at formatting in most of the cases, but it is missing some important functionality for our use case (like adding braces for example). Uncrustify is the most configurable but as well as you have found, it has some quicks here and there, since it is not a compiler. 
You may want to consider clang+uncrustify instead of AStyle. Anyway as you said, the best would be to have just one tool doing all the work :smile:
