### ISSUE TITLE
incorrect newline after first variable in function call within C++ class function definition

### ISSUE THREAD

**Issue by todd-richmond** [uncrustify/uncrustify#447]
Using new sun.cfg from my PR #455, the call to foo(x, y, z) breaks after the first var

    class foo {
    public:
        bool func5(const char *v1, const char *v2, const char *v3)
            { return send(v1, v2, v3); }
    };

which should format to

    class foo {
    public:
        bool func5(const char *v1, const char *v2, const char *v3) {
           return send(v1, v2, v3);
        }
    };

but instead returns

    class foo {
    public:
        bool func5(const char *v1, const char *v2, const char *v3) {
            return send(v1,
                v2, v3);
        }
    };

**Comment by gmaurel** [comment]
The option (in your config file) is set to 1.
# How aggressively to remove extra newlines not in preproc.
# 0: No change
# 1: Remove most newlines not handled by other config

Please test this:
nl_remove_extra_newlines = 0

and report.

**Comment by bengardner** [comment]
May need to update `etc/sun.cfg` again. I get this when trying to test the above:
> The option 'nl_func_var_def_blk' is too big against the option 'nl_max'

In any case, it looks like what is happening is that the newline between the close paren and open brace is removed (due to `nl_fdef_brace=remove`), which then creates a long line.
`code_width=80` hits right after `v1,`. So the line is split there.
```
class foo {
public:
    bool func5(const char *v1, const char *v2, const char *v3) { return send(v1, v2, v3); }
};
```
`nl_after_brace_open=true` didn't take effect before `code_width` because that was detected as a 1-liner and `nl_func_leave_one_liners=true`.

So perhaps what needs to be done is to clear the 1-liner and break the line before attempting to split.
