### ISSUE TITLE
Test 02100 indicating error rather than "unstable" result

### ISSUE THREAD

**Issue by ib** [uncrustify/uncrustify#467]
IMHO, tests/output/c/02100-i2c-core.c already shows an uncrustify bug, because the alignment is wrong:

```
  struct i2c_msg msg[2] = { { addr, flags, 1, msgbuf0 },
                                { addr, flags | I2C_M_RD, 0, msgbuf1 } };
```

It should rather be:

```
  struct i2c_msg msg[2] = { { addr, flags, 1, msgbuf0 },
                            { addr, flags | I2C_M_RD, 0, msgbuf1 } };
```

Even setting indent_braces_no_struct doesn't work in this case (where indent_braces is defined).

**Comment by gmaurel** [comment]
The published fix is not running.
I have to find a new solution for it.
I'll comment out the test for a while.

**Comment by ib** [comment]
> I'll comment out the test for a while.

No, please let's keep it under observation. If you comment out, it might fall from view.

**Comment by mihaipopescu** [comment]
Yes, we need something else... maybe a skip test feature and still have it shown in the console.

On our side, we have a special _staging_ test suite which is used like a separate language. So basically we have a `staging.test` file which is tested separately `./run_tests.sh staging`. This is how we keep track of current regressions and gradually migrate them to the official test suite.

**Comment by ib** [comment]
It's the very purpose of the tests to point out where something is still incorrect. There is nothing wrong with tests being unstable or failing for the moment. Disabled, skipped or removed tests can't aid.

Building and running uncrustify doesn't depend on the tests. It's just an additional, useful feature for people being interested (which developers ought to be).

**Comment by mihaipopescu** [comment]
Hum, I don't think you're just interested in building and running Uncrustify... you should be more interested in what it does.

If you are using Uncrustify on a codebase under source control (I cannot conceive otherwise not even for a personal project) you want it to produce a formatting according to rules and you also want it to be stable, or else it'll just add noise in the history. Every new issue found has to be recorded and tackled at one point depending on its priority/severity.

Uncrustify github project is also using Continuous Integration so it is required that the mainline branch of development passes all the tests (regardless of what the tests are). Unfortunately, this condition was not respected and therefore the failing tests had to be disabled. Issue #560 will try to address this.

That's why it's important to have all tests green but also to have a convenient way to skip tests that are failing because of some mistakes as to always be notified about them along with the the reason why the test was skipped, something like "Known issue #467".

Also, with this, new issues could be submitted to Uncrustify which would ease the reporting and later debugging process. Imagine here that one could create PR's with a new skipped test.

**Comment by ib** [comment]
> so it is required that the mainline branch of development passes all the tests

I disagree.
A **release** has to pass all the tests!
The mainline branch of development has to unveil what bugs (i.e. failing tests) still exist - and not to hide them.

**Comment by scottbilas** [comment]
On Wed, Jul 13, 2016 at 10:45 AM, ib <notifications@github.com> wrote:

> The mainline branch of development has to unveil what bugs (i.e. failing
> tests) still exist - and not to hide them.


No. The mainline must be stable, because that is what others pull. If
Uncrustify had a release process, then I would agree with you, but it does
not. Instead, we have a mainline that is incrementally taking contributions
and fixes, with no regular marking of "stable". Therefore, it must always
be stable.

In other words, the upstream master is *effectively* a continuous release
branch for many working with it. Under no circumstances can it be permitted
to become unstable, which means that 100% of merges must first pass all
tests.

Protect the mainline, and move experimental and stabilizing work to
separate branches.

Scott

**Comment by ib** [comment]
Was I taking about making something unstable? No.
I was talking about having tests unveiling unstableness.

**Comment by scottbilas** [comment]
New tests that are not accompanied by fixes create unstable test results
for everyone else. Tests and fixes must go together, otherwise we end up
with an increasingly useless test report (depending on fix backlog) for new
unrelated code.

Merging a test that is guaranteed to fail, because a fix is not ready yet,
is just going to hurt the process.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
The test 02100 is OK.
Some more comment ?

**Comment by mihaipopescu** [comment]
If the instability is fixed it's fine with me.
