### ISSUE TITLE
for_each is not a C++ keyword

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#531]
Uncrustify 0.63 introduced `for_each` as a C++ keyword thus changing formatting around it.
It matches `std::for_each` function for instance resulting in an unwanted behaviour:

``` c++
void foo()
{
    for_each(it.begin(), it.end(), func);
}
```

becomes:

``` c++
void foo()
{
    for_each (it.begin(), it.end(), func)
        ;
}
```

As seen from the ChangeLog the intention was probably to detect `foreach` Qt keyword/macro.
In any case, I don't think we should be adding Qt _keywords_ as regular C++ keywords.

**Comment by scottbilas** [comment]
Is Qt the only library in existence that has a Q_OBJECT macro? And we're
already running into issues with the Q_FOREACH mapping onto CT_FOR.. Hard
coding Qt into Uncrustify is a maintenance problem. Today we have Qt,
tomorrow will someone want to merge a set of ATL tokens?

It's reasonable to hard code '__style' keywords because that naming
convention is reserved by the C/C++ compiler. Those will always be a
limited group unlikely to have mismatched overloads across compilers. But
special library-specific non-language-keyword tokens is at great risk of
collision with preexisting source code. This will be a definite source of
regressions. Already is.

I think that all CT_Q_* keywords should be removed from Uncrustify and
replaced with a qt.cfg file that can be cfg-included by an end user if they
want to add Qt support. If such a config file is not possible, then add
generic features to Uncrustify that will make it possible. Library-specific
"keywords" really need to be opt-in.

Going forward, great care should be taken before adding anything to that
keyword list.

**Comment by bengardner** [comment]
I agree with Scott here.  We shouldn't add something to the built-in keyword list unless it is part of the language spec.
QT would be better served by including a QT-specific config file that maps custom types.

**Comment by gmaurel** [comment]
OK.
Where could make an example of such a qt.cfg?

**Comment by mihaipopescu** [comment]
I think we can have something like this:

```cfg
mod_qt_keywords = true
set QT_KEYWORD foreach
set QT_KEYWORD Q_EMIT
set QT_KEYWORD Q_FOREACH
set QT_KEYWORD Q_FOREVER
set QT_KEYWORD Q_GADGET
set QT_KEYWORD Q_OBJECT
```

that maps all Qt keywords to a generic Qt keyword and then you can do other tokenization/processing inside Uncrustify.

**Comment by gmaurel** [comment]
Please, make a file of that to do distribute with.

**Comment by mihaipopescu** [comment]
The proposed `mod_qt_keywords` option requires work for a complete new feature. It's not just the config file. We should create a new issue as it's somehow unrelated to this one.

**Comment by gmaurel** [comment]
and ?
As just now, I introduced some QT_ detections.
A config file alone cann't resolved the problem as some (more) changes are necessary to change the flow of the program. The same is working with SQL.

**Comment by mihaipopescu** [comment]
@gmaurel let's continue discussion to the new issue.
