### ISSUE TITLE
Option to have `nl_squeeze_ifdef` to also apply to whole-file #ifdef

### ISSUE THREAD

**Issue by kankaristo** [uncrustify/uncrustify#572]
I just updated from Uncrustify 0.61 to 0.63 and updated my config. The new default file has changed the comment for `nl_squeeze_ifdef`:
```
- # Whether to not put blanks after '#ifxx', '#elxx', or before '#endif'.
+ # Whether to not put blanks after '#ifxx', '#elxx', or before '#endif'. Does not affect the whole-file #ifdef.
```

This seems like not only a changed comment, but also changed behavior. Is there any way to apply `nl_squeeze_ifdef` even to a whole-file #ifdef?

**Comment by gmaurel** [comment]
The change occurs on Feb 20 02:30:37 2015:
nl_squeeze_ifdef should not remove blanks before whole-file #endif.
This was messing up my style.

Is it a problem for you? Please push an example and what you except to get.

**Comment by kankaristo** [comment]
It's not a big problem. I like to have 2 empty lines between function definitions, but I'd like for the whole file `#endif` to "squeeze" the empty lines after the last function definition. This used to happen with 0.61, but not with 0.63.

I have 2 classes which include the definition file into the header (they're template classes, so the definitions need to be in the header) and this is only affecting those 2 .cpp files.

I can live with the extra newlines, just thought I'd report the changed behavior in case it wasn't an intended change.

**Comment by sjakub** [comment]
I just created a pull request: #590 with a new option that makes nl_squeeze_ifdef also squeeze top-level ifdefs.
It also fixes the behaviour of nl_squeeze_ifdef, which was removing a newline before file-level 'endif'.

And changed the comments, since nl_squeeze_ifdef does not skip "whole file" ifdefs, but rather top-level ifdefs. "Whole file" means that the entire file is inside ifdef, but it skips all ifdefs at the highest file level.

**Comment by gmaurel** [comment]
Is merged.
Please test it.
