### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#606]
Currently there are multiple ways of building Uncrustify.

**UNIX** - Gnu autotools (`./autogen.sh; ./configure; make`)
**Windows** - build pre-existing Visual Studio solutions or `make_win32.sh` (is this even used ?)

There are recent efforts to make CMake the single way of building uncrustify and eventually it should replace the other build systems.

Unfortunately I have little to none experience with CMake but I know the documentation and the community around CMake is pretty good and it should be easy to maintain. Taking into account that we already have something working (few issues need to be addressed) I think it should be ok to go with it.

I wanted to ask you @bengardner @gmaurel @scottbilas @sjakub @jibsen if everyone is happy and comfortable with the direction this is heading.

On the other hand, Uncrustify it's a simple project compared with the scale at which CMake is designed for. I also see a high tendency towards Python-based scripting for the scripts in the repository and probably it would make sense to have also a Python-based build system.

There are some out there like [SCons ](http://scons.org/) or [Waf](https://waf.io/). Actually I've seen waf referenced in `.gitignore` even though I have not seen the build script.

One thing to consider is that whatever the chosen build system will be it must be supported by Appveyor and Travis-CI.

**Comment by sjakub** [comment]
I work with cmake-based projects (including cross-platform projects built on Windows as well),
and I really like it. Sometimes it has its issues, but my overall experience is very positive.
It should be easier to just go with cmake instead of maintaining multiple
different build systems.

I don't know about Appveyor and Travis-CI support though.

**Comment by gmaurel** [comment]
The actual CMakeLists.txt is pretty well. But of the issue #600

**Comment by mihaipopescu** [comment]
CMake is quite well supported both by AppVeyor and Travis-CI. Thanks to @jibsen and others the work switching to CMake is almost complete and it's going to happen soon (ETA this week I guess). Based on feedback received so far we can settle on it. We're quite committed with it and it no one else have any other objections I think we should proceed cleaning up the workspace as well of other build systems files.

**Comment by bengardner** [comment]
Many years ago, I tried a few different build systems.  I ended up with autotools because that is what seemed to be used everywhere in the Linux world and it seemed easy to integrate with existing tools.
It is over-kill for such a simple project.

I've never used CMake, but I have no problem with it, as long as it can:
 - do a native Linux build with no fuss
 - cross-compile under Linux, targeting Linux and Windows
 - do a native Windows build (on Windows)
 - do a native OSX build

I don't see a reason to remove the existing build systems or project files until CMake can do all that.
(I've never done the last two bullet items.)

And don't forget building the man pages.

make_win32.sh is the "official" build script for Windows. It cross-compiles (mingw) in a different folder and then creates the release zip.  That's the file that gets uploaded to sourceforge.net.

**Comment by bengardner** [comment]
Oh, and lets not forget that it needs to be able to do native builds on the BSD variants, QNX, Solaris, etc.

**Comment by jibsen** [comment]
I think Autotools is a terrible system, but probably the best option if you are targeting *NIX systems in general, and especially if you need to support old or obscure systems.

CMake is a terrible system as well, but probably the best option currently if you are targeting both modern *NIX systems (including OSX) and Windows (MSVC and others).

> And don't forget building the man pages.

Are there any sources for the man page, or is building it just replacing `@PACKAGE_VERSION@` with the version string?

> make_win32.sh is the "official" build script for Windows. It cross-compiles (mingw) in a different folder and then creates the release zip. That's the file that gets uploaded to sourceforge.net.

There are some instructions for setting up cross-compiling [here](http://www.vtk.org/Wiki/CMake_Cross_Compiling). I am using Fedora, and they [provide a script](https://fedoraproject.org/wiki/MinGW/Tutoria) for running CMake with the cross-compiler set up. Basically, I just did:

~~~.bash
mkdir winbuild
cd winbuild
mingw32-cmake ..
make
~~~

**Comment by jibsen** [comment]
@bengardner, I made a PR (#625) with some changes to allow cross-compiling from Linux to Windows using CMake (and support for creating a zip package similar to what `make_win32.sh` does).

Do you think that could work as a viable alternative for you?

**Comment by mihaipopescu** [comment]
@jibsen I think we should have the cross-compiling build running on the Travis-CI as part of its build matrix. What do you think?

Other than that, I think we're quite ready to do the rollout to cmake.

@bengardner @gmaurel Is there any other objection ?

**Comment by gmaurel** [comment]
It would be fine

**Comment by jibsen** [comment]
> @jibsen I think we should have the cross-compiling build running on the Travis-CI as part of its build matrix. What do you think?

Good idea, I've opened #757 which should add this.
