### ISSUE TITLE
prev->type should be CT_DC_MEMBER

### ISSUE THREAD

**Issue by dzenanz** [uncrustify/uncrustify#620]
In tests 30069 and 30067, the first time `::` is encountered, this token's type is `CT_NONE` but should be `CT_DC_MEMBER`. This caused confusion in pull request #594

**Comment by mihaipopescu** [comment]
Where is the problem ? Are you worried the condition is too loose ? Please provide an example where this bad tokenization produces bad formatted code.

**Comment by dzenanz** [comment]
I was worried that condition is too loose. I will create a pull request to remove the commented out code.

**Comment by mihaipopescu** [comment]
Yeah, I mean, unless you know an example in which the formatting is broken because of this there is no reason to raise this and to commit commented out code. We have git history for that.

On the other hand, maybe Uncrustify should have tokenization tests. Currently bad tokenization produces good formatting results and allegedly good tokenization "fixes" can potentially introduce regressions in production code. It's a total mess but somehow it works. That's one thing we have to figure out.
