### ISSUE TITLE
0.63 breaks pointer alignment

### ISSUE THREAD

**Issue by misery** [uncrustify/uncrustify#643]
If we use uncrustify 0.62 to format this code (example) nothing will be changed as it is expected.

```
class test_Dummy
    : public QObject
{
    Q_OBJECT
    test_Dummy* settings = nullptr;

    Q_PROPERTY(QSortFilterProxyModel* filter READ getFilterModel CONSTANT)

};
```

If we use uncrustify 0.63 we get the following whitespaces at the pointer:

> test_Dummy \* settings = nullptr;
> 
> Q_PROPERTY(QSortFilterProxyModel \* filter READ getFilterModel CONSTANT)

Attached is our uncrustify.cfg
[uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/432375/uncrustify.cfg.txt)

**Comment by gmaurel** [comment]
This is because the star is parsed as CT_ARITH.
I look why.

**Comment by misery** [comment]
Did you find a reason for that? :-)

**Comment by misery** [comment]
Still happens in current git version. :-(

**Comment by misery** [comment]
Ok, I used git bisect to find the changeset. The change of "test_Dummy*" to "test_Dummy *" in first example was introduced in 9f702d6844f1e2793294f6851aa6c19998e9bb85.

Looks like there are multiple problems....

Tested with current git (c4d9ae019be4a86780b6b1fb78b74c8798f83792) add a space.
```
class test_Dummy
	: public QObject
{
	Q_OBJECT
	Q_PROPERTY(QSortFilterProxyModel* filter READ example)
	Q_PROPERTY(QSortFilterProxyModel* filter READ example)

	test_Dummy* settings = nullptr;
};
```

Result:
```
class test_Dummy
	: public QObject
{
	Q_OBJECT
	Q_PROPERTY(QSortFilterProxyModel * filter READ example)
	Q_PROPERTY(QSortFilterProxyModel * filter READ example)

	test_Dummy * settings = nullptr;
};
```

Result of 0.62:
```
class test_Dummy
	: public QObject
{
	Q_OBJECT
	Q_PROPERTY(QSortFilterProxyModel* filter READ example)
	Q_PROPERTY(QSortFilterProxyModel * filter READ example)

	test_Dummy * settings = nullptr;
};
```

**Comment by gmaurel** [comment]
Have a look to https://github.com/uncrustify/uncrustify/pull/787
Only the first part can be solved.

**Comment by gmaurel** [comment]
Q_PROPERTY is a macro for Qt,
  http://doc.qt.io/qt-5/properties.html
uncrustify doesn't know what a macro is for, what the parameters are

**Comment by simonbrunel** [comment]
@gmaurel I'm experiencing the same issue with the Qt macro and I'm wondering why in this very specific case (Q_PROPERTY), the star is centered while pointer stars are expected (configured) to be aligned on type (left), ? What uncrustify rule imply that formatting?

**Comment by CDanU** [comment]
Because in this case Uncrustify thinks this is an arithmetic star as in `int i = 5 * 5;`. 
Therefore `sp_arith = force` is applied instead of `sp_before_ptr_star = remove`.

It is generally hard to correctly process macros without knowing how they are defined. Most of the time they look like normal function calls, if they don't we can't easily define what to do about them. 
One thing that can be done is basically to give Uncrustify hints about what type a specific token is and hope that it has enough patterns to apply the correct formatting. In this specific case adding
`type QSortFilterProxyModel` to the config will do that.

**Comment by simonbrunel** [comment]
@CDanU thanks, that makes sense! I'm sure how to properly workaround that case since we can't list all `type*` that could be used in `Q_PROPERTY`. Is there any way to exclude (skip formatting) some patterns via the options (e.g. `ignore = ^Q_PROPERTY\(.+?\)$`)?

I'm trying to setup uncrustify to only detect coding style errors during CI process and report PR not mergeable if there is a difference between the formatted and submitted file. I don't want to drop `sp_arith = force` but would be fine to ignore style for some specific macros.

**Comment by CDanU** [comment]
No there is no formatting disabling based on regex expressions or any kind of other patterns. Currently the formatting can only be disabled based on comments (see enable/disable_processing_cmt options), for defines of macro functions (`pp_ignore_define_body`) and asm code blocks.

It should however be fairly easy to implement a new token type which disables processing following pattern: `word(*)`
Something like `set `IGNORE_XXX  Q_PROPERTY` would than ignore the Q_PROPERTY and everything that is included in the following parenthesis pair.
