### ISSUE TITLE
make_version.py issues

### ISSUE THREAD

**Issue by jibsen** [uncrustify/uncrustify#776]
As mentioned in #769, `make_version.py` does not appear to work from its new location in the scripts folder. The issues I noticed were:
- print needs parenthesis for Python 3 compatibility
- `scripts/tokenize.py` shadows a system module that `make_version.py` includes
- it insists on looking for `.git` in the same folder as the script rather than it's working folder

**Comment by mihaipopescu** [comment]
I don't think this is fixed. We should reopen this one and take a look.

**Comment by mihaipopescu** [comment]
@jibsen Thanks for checking this. I have few questions.

> print needs parenthesis for Python 3 compatibility

I don't think it does. I have Python 2.7 and it works. Can you elaborate why do you think otherwise?


> scripts/tokenize.py shadows a system module that make_version.py includes

I don't understand. I don't see any connection between the two scripts.

@gmaurel Can you reopen this issue ? Also pretty please don't close issues that don't have any resolution (like this one) as they can get lost. If you really want to do it you can add a comment with a reason why.

**Comment by jibsen** [comment]
In Python 3, [print is a function](https://docs.python.org/3.0/whatsnew/3.0.html#print-is-a-function), so it requires parenthesis. In order for the script to work with both Python 2 and 3, we need to add parenthesis.

For better or worse, Python files in the local folder may [shadow Python modules](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap). `make_version.py` imports subprocess, which somewhere down the line inside the Python 3 libraries imports tokenize. Python 2 does not import this, but you can get the same effect if for instance you create a file `threading.py` in the scripts folder containing only the word raise. Basically, since this isn't a package with its own namespace, I think we'll need to steer clear of any filenames that might shadow Python libraries.
