### ISSUE TITLE
Being able to change only one precise aspect of the code

### ISSUE THREAD

**Issue by swilmet** [uncrustify/uncrustify#820]
Uncrustify has a lot of options. It would be nice to ignore all options except one. That is, keep the code as-is except for the specific option that I want to change.

To give an example: add curly braces around all blocks of code, even if the block contains only one line. Do only that, do not change the rest.

If Uncrustify can do this, it would be a much more powerful and flexible tool.

**Comment by CDanU** [comment]
A noop config, the case of having no options, is not useful and is likely caused by an user error. Therefore an error message should be thrown if zero options are set.

Having no default settings is what you actually want. I too would really like this to happen at some point.

As of now defaults are set by set_option_defaults() function in the options.cpp which itself is called by the main function.
I assume that it would be a significant amount of work to restructure everything that depends on these settings being set.

**Comment by mihaipopescu** [comment]
I think historically Uncrustify was not designed to have a null config. There are a lot of things happening which are not controlled by any option. Basically the defaults are there to preserve old behavior when a new option is added.

**Comment by gmaurel** [comment]
It is not the same:

- an empty config file or with linux use of /dev/null as a config

- a null config.
In the first case, all the default values are used,
The second case wished "no change" at all. This is not possible with uncrustify.
Lot of options accept value True/False. These cannot accept "ignore".

**Comment by stefan-nu** [comment]
In my opinion a "null" configuration would be useful.

It should leave all input code unchanged. As if all code was surrounded by INDENT-OFF / INDENT-ON

- It would ease testing single options
- It would make uncrustify easier for new users
- It would help to modify very specific parts of a code base only
- It might help to call uncrustify from other tools which might use automatically generated config files
- StackOverflow lists at least twice a question regarding this feature. It seems to be wanted by others as well

But I understand that a null configuration is currently not expected and might be difficult to realize.

Nevertheless imho this would at least be a feature to be considered in the future.

**Comment by swilmet** [comment]
See this comment, it is related to the problem here:
https://github.com/uncrustify/uncrustify/issues/749#issuecomment-268972550

**Comment by swilmet** [comment]
I guess that fixing this would probably need a complete rewrite of the tool.

Maybe someone else can start implementing such a tool. Put aside the performances, focus on modularity and flexibility. Each option would basically do one pass on the code, change only one aspect of it. Several options means doing several passes. The performances would maybe be horrible, but such a tool would be more powerful. Think of it as something that you run only once in a while, not every time that the code is modified.

**Comment by mwoehlke-kitware** [comment]
To work as you suggest *would* require a complete rewrite.

The way uncrustify works (and I would suspect clang-format also) is to convert your source into an abstract representation, and then convert it back. There is quite a bit of whitespace information preserved in the representation, which allows preserving existing format in many cases, but perhaps not all.

My suggestion would be to play around with an all-defaults configuration, identify what, if any, changes are happening in that mode, and individually raise issues about those. If you start with input that is not changed in this mode, then you already *can* try out individual options... with a caveat; some options can interact with each other and have a different effect when both are in use compared to only one in use.

You could also try creating your own "null" configuration by setting some of the options with default values to `ignore`. This won't work for `true`/`false` options, and some (e.g. `output_tab_size`) simply can't have a meaningful "ignore" value, but there are others (e.g. `sp_pp_concat`) that you can change. Note that, since the [Great Option Refactoring](../pull/1852), there is no single function to set default values, which now appear with the option declaration. You can find them easily by searching for "; // =" in [options.h](../tree/master/src/options.h).
