### ISSUE TITLE
Regression in align_oc_msg_colon_span rule

### ISSUE THREAD

**Issue by daniel-beard** [uncrustify/uncrustify#841]
- The newest version of uncrustify (0.64) appears to have incorrect behavior here.

Example file: (test.m)
```obj-c
- (void)myMethod {
    NSInteger rowCount = [sectionProvider collectionView:self.collectionView
    numberOfRowsInSection:section];
}
```

Configuration file: 
```
align_oc_msg_colon_span        = 1
```

Output for version 0.64 (incorrect): [Debug Log File](https://gist.github.com/daniel-beard/11cdb323ef53f99042617afcf6b8b02f)
```
- (void)myMethod {
	NSInteger rowCount = [sectionProvider collectionView:self.collectionView
	                               numberOfRowsInSection       :section];
}
```

Output for version 0.60 (correct):
```
- (void)myMethod {
	NSInteger rowCount = [sectionProvider collectionView:self.collectionView
	                               numberOfRowsInSection:section];
}
```

- Was there a change to the behavior of the `align_oc_msg_colon_span` rule that I'm not aware of, or is this a legitimate issue? 

EDIT: Git bisect appears to point to this commit as the point where the behavior changed: https://github.com/uncrustify/uncrustify/commit/b4c8b3610166b580f557e0f90f9c091b63830e25

**Comment by mihaipopescu** [comment]
That's quite an old change. As commented on another ObjC related issue, we have a lot of Objective-C fixes that need some work to be pushed upstream. We'll have to see when we can get to work on them. For some reason they are not in our top priority. You can find them here https://github.com/Unity-Technologies/uncrustify/tree/fixes/c-oc-java if you want to take a look to see if your issue is still reproducing on that branch.

**Comment by guy-maurel** [comment]
Sorry for the delay to solve the bug.
We have too few persons to work on it.

This is not a bug, but a new option was introduced on Oct 24 02:19:07 2013
It is for your source to use this:
`indent_oc_msg_prioritize_first_colon = false`

Thanks for the message.
