### ISSUE TITLE
Instabilities as failures

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#907]
I've seen that we are introducing instabilities and we may not even notice because of the build system doesn't treat them as errors. Having instabilities in the code is just as bad as having formatting errors or, in some use-cases like our own (format at merge/commit time), they are actually more harmful.

What the test framework should do:
- [x] treat instability warnings as errors
- [x] create issues for each instability
- [ ] create a whitelist to mark known instabilities and ignore them
- [ ] add a build configuration (for final release) that doesn't use the whitelist (warnings will show up as errors)

We could also use this feature to whitelist known staging formatting errors. Fixing an error/instability should also be accompanied by removing it from the whitelist.

Actually we are already using this kind of workflow on our side. We have a `staging.test` and `regression.test` test files. In staging test file we collect all issues we would like to fix. When an issue gets fixed it's moved to the regression file. It may not be the best workflow but it works out of the box with the current test framework.

**Comment by CDanU** [comment]
Can we actually remove all instabilities? I don't see how we could for example fix `nl_before_func_body_def` ([see the example in PR 904](https://github.com/uncrustify/uncrustify/pull/904#issuecomment-271321525)) if we want to keep Uncrustify deterministic and insert newlines only behind the description comment.

Additionally to the improved build system this _solutions_ should be considered:
* completely remove all options that have instabilities
* allow those options only when Uncrustify is running in an _unsafe_ mode
* restrict the values of options so that no instabilities can happen

**Comment by mihaipopescu** [comment]
I'd like to remove them all but I think that's a big task to start with. I like the `--unsafe` flag to enable certain unstable options only if they are not part of an option combination as it will complicate the feature.

What we could do at first is to make a note of them and create high priority issues and make sure we're not adding new ones.

> With +500 options we will never find all instabilities.
We could use a fuzzer for that.

**Comment by gmaurel** [comment]
There is an instability one cannot remove.
Let us have a look at number 30265,
first pass of uncrustify add the comment ```} // foo::bar```
second run aligns it with the line before:
```
      } // switch
   }    // foo::bar
```

**Comment by mihaipopescu** [comment]
Sightly offtopic but I've just stumbled on htt ps://github.com/llvm-mirror/clang/blob/master/tools/clang-format/fuzzer/ClangFormatFuzzer.cpp

**Comment by mihaipopescu** [comment]
I haven't checked this lately but how many instabilities we still have? Can we turn them on as failures?

**Comment by guy-maurel** [comment]
We don't have any more instabilities.
We can close.

**Comment by mihaipopescu** [comment]
So then it's a good time to turn instabilities as errors. What do you think?

**Comment by gmaurel** [comment]
Could you point to a current problem?

**Comment by mihaipopescu** [comment]
If we are not going to treat instabilities as errors in our testing suite, they will slowly creep in and make uncrustify .. unstable. We need to modify the testing framework to produce an error when an instability is detected and not a warning as they used to be.

**Comment by guy-maurel** [comment]
Correct.
But do we have any instability just now?

**Comment by CDanU** [comment]
Yes we still have a bunch as we never did anything to solve them. Currently only(?) `run_tests.py` does show that status. I agree however that we should start treating instabilities as errors whilst ignoring the current unsolved ones. This way we at least won't get any new instabilities.

**Comment by mihaipopescu** [comment]
Then let's turn new-instabilities-as-errors by whitelisting these ones and create issues each of them.

**Comment by mwoehlke-kitware** [comment]
I think this is a good time to revisit this, particularly in light of #1821... essentially, I'd like to have a definitive conclusion to https://github.com/uncrustify/uncrustify/pull/1799#discussion_r195225473.

Right now, CTest *does* treat instabilities as errors, and with #1807, it will finally be running all tests that the old `run_tests.py` would run.

The difference is with tests that have separate re-run config and expected output. CTest (and #1821) do the second passes on these using the expected re-run output as the input, while old `run_tests.py` uses the expected output from the first pass. In fact, now that I look closer, I see that the difference is basically that, while both substitute the re-run *config*, only CTest also substitutes the re-run *expected output*. (Note: this only applies to tests marked with `!` which use the separate re-run config.)

This does suggest that the change in behavior for CTest was intentional, and thus that that is the behavior we want to keep going forward. If that is the case, than I think this issue can be closed, or at least the first and third tasks checked, since CTest (before or after #1821) *is* treating instabilities as failures, and — using the CTest version of special handling for the handful of tests that need it — we don't currently have any failures.

I don't think we need the second task ("create issues for each instability"). We only have eight tests currently with separate re-run configs, and I don't anticipate this number increasing significantly. For the existing ones, we can create issues manually, if warranted, and for any new ones, I think it would be okay to ask the PR author to open an issue if adding a test that needs special re-run handling.

That would leave the fourth task... and it might be interesting to add an option (probably post-#1821) to disable the special re-run handling in order to see what's going on with those tests.

**Comment by mwoehlke-kitware** [comment]
Ping again... what, if anything, are the still-open issues here? Can we close this?

> it might be interesting to add an option (probably post-#1821) to disable the special re-run handling in order to see what's going on with those tests.

I ended up doing this by hand (and filing issues — #1907, #1908, #1909 — for the real stability problems; yay!), and since I don't expect an influx of new ones, I don't see any pressing need at this time to add such an option. (Of course, if someone else wants to do it, patches are welcome, but don't anyone hold their breath hoping *I'll* do it. :wink: There are plenty of other issues higher on my priority list.)

**Comment by mihaipopescu** [comment]
Thanks @mwoehlke-kitware !
