### ISSUE TITLE
Adding additional exclusion patterns to .gitignore

### ISSUE THREAD

**Issue by stefan-nu** [uncrustify/uncrustify#917]
I would like to propose to add some more exclusion patterns to .gitignore.

The automatically generated files should be excluded. In the current version of .gitignore there are already entries but they are commented.
```
#src/token_names.h
#src/uncrustify_version.h
```
Is there any reason why those are commented. If not could they be activated again?

I would also propose to add the following lines
```
# UNIX build artifacts
*.[oaisS]

# Testing framework
results/

# Eclipse Build Directories
Debug/
Release/
```

**Comment by CDanU** [comment]
I guess those where commented out because starting with release 0.64 uncrustify is using cmake.
The generated files should be in the directory where you execute cmake. This directory should be `build` as it is hard coded into `Run_uncrustify_for_sources.sh`.

I also use eclipse cdt and have an private orphan branch that holds all the files that are needed to build with eclipse (including the auto generated files). 

Additionally to the ones mentioned this would be:
* `src/config.h`
* `.cproject`
* `.project`
* `.settings`

**Comment by gmaurel** [comment]
Fine. Make a PR.

**Comment by stefan-nu** [comment]
.gitignore has been updated. Ticket gets closed.
