### ISSUE TITLE
-p option broken

### ISSUE THREAD

**Issue by dfaure-kdab** [uncrustify/uncrustify#930]
I tried to generate a debug file as indicated in the github new-issue instructions, but

uncrustify -p debug.txt --no-backup -c /tmp/uncrustify-kf5.cfg authinfo.cpp

does not generate a debug.txt file. `strace` confirms that nothing happens to a file named debug.txt, even in some other dir or something. Is the -p functionality broken?

Uncrustify version 0.63 8e94389

**Comment by CDanU** [comment]
Yes that one exits quiet some time now. The problem is that currently you have to specify the input file with -f. The formatted file will be printed to stdout so you should drop the --no-backup.

> uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp

**Comment by dfaure-kdab** [comment]
OK, thanks for the workaround. It's still a bug though, surely -p can work also when not using -f (and otherwise it should abort with an error and tell the user to use -f).

**Comment by CDanU** [comment]
Why was this one closed? I too think that this is an legitimate issue.

Look at [do_source_file in uncrustify.cpp:781](https://github.com/uncrustify/uncrustify/blob/6315cb3b5d980ea5d62d2081612c915fa03472b1/src/uncrustify.cpp#L781) inside the main function. Here 3rd param passed to `do_source_file` is `NULL` instead of the available `parsed_file` var.

This looks like an easy solution to deal with the problem that because `do_source_file`, which is called in a loop, and the thereafter following `process_source_list` process multiple files. Every single file would need a different name for its debug output.

How should we solve this?

1.  Adding a suffix to the specified `-p` option input and check before writing the output to the disk that no files with the same name already exist.
2.  Throw an error message for `-p` if multiple files are processed (i.e. only allow using `-p` with `-f`).

**Comment by mihaipopescu** [comment]
Agree with @CDanU. Let's kindly ask @gmaurel to reopen.

**Comment by guy-maurel** [comment]
#1798 is a bugfix proposal

**Comment by gmaurel** [comment]
Fixed
