### ISSUE TITLE
Detecting and fixing all "Dereferencing NULL pointer" errors

### ISSUE THREAD

**Issue by stefan-nu** [uncrustify/uncrustify#940]
During the last weeks, were reportet three bugs caused by derefererencing a Null pointer (#938, #916, #859).
@mihaipopescu pointed out, that most often the Null pointer dereferencing is not the root cause of the bug. This might well be the case and often the fix is more complicated than just adding a check for a NULL pointer.

Nevertheless I feel that any such crash is one too much. For a user it is disappointing to experiance such behaviour. We are lucky that some users take the effort to report the issue. I'd assume for every reported issue there are several other users that just stop using uncrustify because they think it is a buggy tool.
That said, I think it is important to prevent such crashes.
Thus in my opinion a pointer that cannot be garanteed to be valid has always to be checked. It is then up to the programmer to either print a warning, exit the program with a useful error message or slilently continue the program exection.

When I check the sourcecode with pclint I get thousands of errors/warnings and many of those refer to possible Null pointer dereferencing. My experiance is that pclint is rather precise and most of those warnings are real bugs. That said I feel we have to spend some time fixing those issues before each line gets reported by a disappointed user.

I am willing to go into this task even though I know it will be a big one and it will take quite some time to terminate.

pclint is a commercial tool that it is presumably not available to every developer. Anyway would you agree that I add a configuration for pclint to the test directory? Everyone who has access to the tool may then check his code. For all others its just a directory to ignore.

**Comment by mihaipopescu** [comment]
`cppcheck` can be an alternative. Also, I think @gmaurel has already done a pass with a static analysis tool (unsure if it was coverity or something else).

Later maybe we could consider fuzz testing. And what about a crazy idea of formatting source code from github ? It could help to reveal a lot of issues.

**Comment by stefan-nu** [comment]
I am using `cppcheck`. It is a nice tool. And in my opinion it should be used as an entry level tool by everyone. But by no means it is comparable to `pclint`. 

To show you the difference I attache the check output for commit 6315cb3b5d of `cppcheck` and `pclint` respectively:
[cppcheck-results.txt](https://github.com/uncrustify/uncrustify/files/716738/cppcheck-results.txt)
[pclint-results.txt](https://github.com/uncrustify/uncrustify/files/716737/pclint-results.txt)

`Coverity` is more or less comparable to `pclint`. But I don't see where it (or another tool) is used to check uncrustify so far.

Fuzz testing might be helpful to detect program crashes. But this makes only sense after the obvious issues have been fixed. Otherwise fuzz testing will simple tell us that there are issues which is what we know already now.

I don't know what you mean with "formatting source code from github".

**Comment by CDanU** [comment]
Search for [coverity](https://github.com/uncrustify/uncrustify/search?utf8=%E2%9C%93&q=Coverity) in this repo. There I found this link: [coverity.com/projects/uncrustify](https://scan.coverity.com/projects/uncrustify).

**Comment by gmaurel** [comment]
I had a look to the output of Coverity some months ago.
There don't where many errors found.

**Comment by jibsen** [comment]
It seems like these errors all origin from the direct use of (and failure to check) the next and prev pointers in chunk_t.

**Comment by jrosenberger** [comment]
"I don't know what you mean with "formatting source code from github"."

I think he means using github as a source for test cases.

**Comment by mihaipopescu** [comment]
Yeah. A web crawler could collect code from opensource projects and format them with some default rules.

**Comment by stefan-nu** [comment]
@mihaipopescu Are you serious or just kidding? I never saw a web crawler formatting code. But if that exists I am curious about it.

**Comment by mihaipopescu** [comment]
@stefan-nu I'm just throwing out random ideas on how to extend our test data set for testing stability / not correctness. I think there are Data Mining APIs that can be used (I guess even GitHub might have something for this) to retrieve open source code.

**Comment by stefan-nu** [comment]
Ahhh I think now I got it. You want to collect a large amount of source code. Then you feed it to uncrustify and check if it will crash. Great idea.

**Comment by todd-richmond** [comment]
cppcheck with --enable=all might find a bit more if you did not have that enabled

cppcheck --enable=all --force --inline-suppr -I incude_path *

In general, I have always found it better to NOT add null checks to random code that should never see a null. The problem is that you are just papering over the real error so the program ends up crashing well after the initial bug because several intervening null checks let the program "proceed". It's far better to crash immediately where you have exact context than it is to do so later (and you will eventually crash somewhere else regardless)

**Comment by jibsen** [comment]
While I agree some NULL checks hide issues, and sometimes an assert is better if something should not be NULL, I think some of these are due to the chunk list being a doubly linked list, and there isn't really any way around checking if you are at the beginning or end of the list before accessing the previous and next element.

The question is if there is a better way to handle this than having to remember to write the check in every place the prev and next pointers are used.

**Comment by mihaipopescu** [comment]
I'm not sure if there is a better way. Uncrustify is a rather complicated machinery dealing with global variables having a formatting process quite dynamic... so because of some made assumptions still things can go wrong. But rarely I've seen a crash be hard to debug and to fix.

The underlying issue here is that most of the times and mainly because of the lack of enough context, uncrustify gracefully continues and tokenizes the code in a wrong way (like `CT_ARITH` instead of reference or pointer). These are the nasty issues that are simply lurking and waiting to be discovered and fixed.

So I think we would still need to check ahead for previous and next elements where it makes sense and make sure we're not gracefully continue when we discover a bad sequence and complain loudly (like in the case of unmatched closed brace recently added).
