### ISSUE TITLE
adopt some changes from UT

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#963]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
The sources from https://github.com/Unity-Technologies/uncrustify.git give us many useful patches.
It is now very difficult to merge with uncrustify master.
Having a look to the test list 'regression.test', one can see 46 tests.
The most of them are already implemented. Only few of them are the prove of a bug.
This is the first of the list.

Having:
```
class C<T1, T2, TX, T3, T4, T5>
        : IDisposable, IEnumerable<T1>
        where T1 : class, D, E, new()
                where T2 : IDictionary<D, Dictionary<string, float>>
                        where TX : struct, IDisposable
                                where T3 : class
                                                where T4 : D where T5 : E
{
        void F<T3, T4, T5, TX, T6>()  where T3 : D, new()
        where T4 : D
        where T5 : D
        where TX : new()
        where T6 : D
        {
        }
}
```
with a conffiguration
```
indent_class=true
sp_angle_shift=remove
sp_inside_angle=remove
sp_after_comma=add
```
we expect:
```
class C<T1, T2, TX, T3, T4, T5>
	: IDisposable, IEnumerable<T1>
	where T1 : class, D, E, new()
	where T2 : IDictionary<D, Dictionary<string, float>>
	where TX : struct, IDisposable
	where T3 : class
	where T4 : D where T5 : E
{
	void F<T3, T4, T5, TX, T6>()  where T3 : D, new()
	    where T4 : D
	    where T5 : D
	    where TX : new()
	    where T6 : D
	{
        }
}
```

**Comment by mihaipopescu** [comment]
I wanted to clarify something. @gmaurel, you said:

> The most of them are already implemented. Only few of them are the prove of a bug.

The bugs that you're seeing from `regression.test` file are not bugs on our side. They are fixed on our side but we've not managed to clean and push them upstream. That's why we're running this regression suite part of the  https://github.com/Unity-Technologies/uncrustify/blob/master/tests/CMakeLists.txt#L21 to avoid any further regressions.

For this change, if I understand correctly you looked at https://github.com/Unity-Technologies/uncrustify/blob/master/tests/regression.test#L15, this is already fixed on our side.

@gmaurel Please take a look instead at https://github.com/Unity-Technologies/uncrustify/blob/master/tests/staging.test suite where we've collected our real standing issues.

I'm sorry if you misunderstood our workflow.
